// Code generated by protoc-gen-go-opaque-helpers. DO NOT EDIT.
// source: dapmux/v1/dapmux.proto

package dapmuxv1

import (
	protovalidate "buf.build/go/protovalidate"
)

// NewRegisterTargetRequest creates a new RegisterTargetRequest using the builder
func NewRegisterTargetRequest(b *RegisterTargetRequest_builder) *RegisterTargetRequest {
	return b.Build()
}

// NewRegisterTargetRequestE creates a new RegisterTargetRequest using the builder with validation
func NewRegisterTargetRequestE(b *RegisterTargetRequest_builder) (*RegisterTargetRequest, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewRegisterTargetResponse creates a new RegisterTargetResponse using the builder
func NewRegisterTargetResponse(b *RegisterTargetResponse_builder) *RegisterTargetResponse {
	return b.Build()
}

// NewRegisterTargetResponseE creates a new RegisterTargetResponse using the builder with validation
func NewRegisterTargetResponseE(b *RegisterTargetResponse_builder) (*RegisterTargetResponse, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewUnregisterTargetRequest creates a new UnregisterTargetRequest using the builder
func NewUnregisterTargetRequest(b *UnregisterTargetRequest_builder) *UnregisterTargetRequest {
	return b.Build()
}

// NewUnregisterTargetRequestE creates a new UnregisterTargetRequest using the builder with validation
func NewUnregisterTargetRequestE(b *UnregisterTargetRequest_builder) (*UnregisterTargetRequest, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewUnregisterTargetResponse creates a new UnregisterTargetResponse using the builder
func NewUnregisterTargetResponse(b *UnregisterTargetResponse_builder) *UnregisterTargetResponse {
	return b.Build()
}

// NewUnregisterTargetResponseE creates a new UnregisterTargetResponse using the builder with validation
func NewUnregisterTargetResponseE(b *UnregisterTargetResponse_builder) (*UnregisterTargetResponse, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewListTargetsRequest creates a new ListTargetsRequest using the builder
func NewListTargetsRequest(b *ListTargetsRequest_builder) *ListTargetsRequest {
	return b.Build()
}

// NewListTargetsRequestE creates a new ListTargetsRequest using the builder with validation
func NewListTargetsRequestE(b *ListTargetsRequest_builder) (*ListTargetsRequest, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewListTargetsResponse creates a new ListTargetsResponse using the builder
func NewListTargetsResponse(b *ListTargetsResponse_builder) *ListTargetsResponse {
	return b.Build()
}

// NewListTargetsResponseE creates a new ListTargetsResponse using the builder with validation
func NewListTargetsResponseE(b *ListTargetsResponse_builder) (*ListTargetsResponse, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewSetActiveTargetRequest creates a new SetActiveTargetRequest using the builder
func NewSetActiveTargetRequest(b *SetActiveTargetRequest_builder) *SetActiveTargetRequest {
	return b.Build()
}

// NewSetActiveTargetRequestE creates a new SetActiveTargetRequest using the builder with validation
func NewSetActiveTargetRequestE(b *SetActiveTargetRequest_builder) (*SetActiveTargetRequest, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewSetActiveTargetResponse creates a new SetActiveTargetResponse using the builder
func NewSetActiveTargetResponse(b *SetActiveTargetResponse_builder) *SetActiveTargetResponse {
	return b.Build()
}

// NewSetActiveTargetResponseE creates a new SetActiveTargetResponse using the builder with validation
func NewSetActiveTargetResponseE(b *SetActiveTargetResponse_builder) (*SetActiveTargetResponse, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewStreamTargetEventsRequest creates a new StreamTargetEventsRequest using the builder
func NewStreamTargetEventsRequest(b *StreamTargetEventsRequest_builder) *StreamTargetEventsRequest {
	return b.Build()
}

// NewStreamTargetEventsRequestE creates a new StreamTargetEventsRequest using the builder with validation
func NewStreamTargetEventsRequestE(b *StreamTargetEventsRequest_builder) (*StreamTargetEventsRequest, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewForwardDAPMessageRequest creates a new ForwardDAPMessageRequest using the builder
func NewForwardDAPMessageRequest(b *ForwardDAPMessageRequest_builder) *ForwardDAPMessageRequest {
	return b.Build()
}

// NewForwardDAPMessageRequestE creates a new ForwardDAPMessageRequest using the builder with validation
func NewForwardDAPMessageRequestE(b *ForwardDAPMessageRequest_builder) (*ForwardDAPMessageRequest, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewForwardDAPMessageResponse creates a new ForwardDAPMessageResponse using the builder
func NewForwardDAPMessageResponse(b *ForwardDAPMessageResponse_builder) *ForwardDAPMessageResponse {
	return b.Build()
}

// NewForwardDAPMessageResponseE creates a new ForwardDAPMessageResponse using the builder with validation
func NewForwardDAPMessageResponseE(b *ForwardDAPMessageResponse_builder) (*ForwardDAPMessageResponse, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewTarget creates a new Target using the builder
func NewTarget(b *Target_builder) *Target {
	return b.Build()
}

// NewTargetE creates a new Target using the builder with validation
func NewTargetE(b *Target_builder) (*Target, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewConnectionInfo creates a new ConnectionInfo using the builder
func NewConnectionInfo(b *ConnectionInfo_builder) *ConnectionInfo {
	return b.Build()
}

// NewConnectionInfoE creates a new ConnectionInfo using the builder with validation
func NewConnectionInfoE(b *ConnectionInfo_builder) (*ConnectionInfo, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewTargetEvent creates a new TargetEvent using the builder
func NewTargetEvent(b *TargetEvent_builder) *TargetEvent {
	return b.Build()
}

// NewTargetEventE creates a new TargetEvent using the builder with validation
func NewTargetEventE(b *TargetEvent_builder) (*TargetEvent, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewHealthCheckRequest creates a new HealthCheckRequest using the builder
func NewHealthCheckRequest(b *HealthCheckRequest_builder) *HealthCheckRequest {
	return b.Build()
}

// NewHealthCheckRequestE creates a new HealthCheckRequest using the builder with validation
func NewHealthCheckRequestE(b *HealthCheckRequest_builder) (*HealthCheckRequest, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewHealthCheckResponse creates a new HealthCheckResponse using the builder
func NewHealthCheckResponse(b *HealthCheckResponse_builder) *HealthCheckResponse {
	return b.Build()
}

// NewHealthCheckResponseE creates a new HealthCheckResponse using the builder with validation
func NewHealthCheckResponseE(b *HealthCheckResponse_builder) (*HealthCheckResponse, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}
