// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dapmux/v1/dapmux.proto

package dapmuxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Target status enumeration
type TargetStatus int32

const (
	TargetStatus_TARGET_STATUS_UNSPECIFIED  TargetStatus = 0
	TargetStatus_TARGET_STATUS_ACTIVE       TargetStatus = 1
	TargetStatus_TARGET_STATUS_DISCONNECTED TargetStatus = 2
	TargetStatus_TARGET_STATUS_ERROR        TargetStatus = 3
	TargetStatus_TARGET_STATUS_CONNECTING   TargetStatus = 4
	TargetStatus_TARGET_STATUS_RECONNECTING TargetStatus = 5
)

// Enum value maps for TargetStatus.
var (
	TargetStatus_name = map[int32]string{
		0: "TARGET_STATUS_UNSPECIFIED",
		1: "TARGET_STATUS_ACTIVE",
		2: "TARGET_STATUS_DISCONNECTED",
		3: "TARGET_STATUS_ERROR",
		4: "TARGET_STATUS_CONNECTING",
		5: "TARGET_STATUS_RECONNECTING",
	}
	TargetStatus_value = map[string]int32{
		"TARGET_STATUS_UNSPECIFIED":  0,
		"TARGET_STATUS_ACTIVE":       1,
		"TARGET_STATUS_DISCONNECTED": 2,
		"TARGET_STATUS_ERROR":        3,
		"TARGET_STATUS_CONNECTING":   4,
		"TARGET_STATUS_RECONNECTING": 5,
	}
)

func (x TargetStatus) Enum() *TargetStatus {
	p := new(TargetStatus)
	*p = x
	return p
}

func (x TargetStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_dapmux_v1_dapmux_proto_enumTypes[0].Descriptor()
}

func (TargetStatus) Type() protoreflect.EnumType {
	return &file_dapmux_v1_dapmux_proto_enumTypes[0]
}

func (x TargetStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Target event types
type TargetEventType int32

const (
	TargetEventType_TARGET_EVENT_TYPE_UNSPECIFIED            TargetEventType = 0
	TargetEventType_TARGET_EVENT_TYPE_ADDED                  TargetEventType = 1
	TargetEventType_TARGET_EVENT_TYPE_REMOVED                TargetEventType = 2
	TargetEventType_TARGET_EVENT_TYPE_STATUS_CHANGED         TargetEventType = 3
	TargetEventType_TARGET_EVENT_TYPE_METADATA_UPDATED       TargetEventType = 4
	TargetEventType_TARGET_EVENT_TYPE_CONNECTION_ESTABLISHED TargetEventType = 5
	TargetEventType_TARGET_EVENT_TYPE_CONNECTION_LOST        TargetEventType = 6
)

// Enum value maps for TargetEventType.
var (
	TargetEventType_name = map[int32]string{
		0: "TARGET_EVENT_TYPE_UNSPECIFIED",
		1: "TARGET_EVENT_TYPE_ADDED",
		2: "TARGET_EVENT_TYPE_REMOVED",
		3: "TARGET_EVENT_TYPE_STATUS_CHANGED",
		4: "TARGET_EVENT_TYPE_METADATA_UPDATED",
		5: "TARGET_EVENT_TYPE_CONNECTION_ESTABLISHED",
		6: "TARGET_EVENT_TYPE_CONNECTION_LOST",
	}
	TargetEventType_value = map[string]int32{
		"TARGET_EVENT_TYPE_UNSPECIFIED":            0,
		"TARGET_EVENT_TYPE_ADDED":                  1,
		"TARGET_EVENT_TYPE_REMOVED":                2,
		"TARGET_EVENT_TYPE_STATUS_CHANGED":         3,
		"TARGET_EVENT_TYPE_METADATA_UPDATED":       4,
		"TARGET_EVENT_TYPE_CONNECTION_ESTABLISHED": 5,
		"TARGET_EVENT_TYPE_CONNECTION_LOST":        6,
	}
)

func (x TargetEventType) Enum() *TargetEventType {
	p := new(TargetEventType)
	*p = x
	return p
}

func (x TargetEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_dapmux_v1_dapmux_proto_enumTypes[1].Descriptor()
}

func (TargetEventType) Type() protoreflect.EnumType {
	return &file_dapmux_v1_dapmux_proto_enumTypes[1]
}

func (x TargetEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Health status enumeration
type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNKNOWN         HealthStatus = 0
	HealthStatus_HEALTH_STATUS_SERVING         HealthStatus = 1
	HealthStatus_HEALTH_STATUS_NOT_SERVING     HealthStatus = 2
	HealthStatus_HEALTH_STATUS_SERVICE_UNKNOWN HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNKNOWN",
		1: "HEALTH_STATUS_SERVING",
		2: "HEALTH_STATUS_NOT_SERVING",
		3: "HEALTH_STATUS_SERVICE_UNKNOWN",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNKNOWN":         0,
		"HEALTH_STATUS_SERVING":         1,
		"HEALTH_STATUS_NOT_SERVING":     2,
		"HEALTH_STATUS_SERVICE_UNKNOWN": 3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_dapmux_v1_dapmux_proto_enumTypes[2].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_dapmux_v1_dapmux_proto_enumTypes[2]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Target registration request
type RegisterTargetRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ProcessName string                 `protobuf:"bytes,1,opt,name=process_name,json=processName"`
	xxx_hidden_DelveAddr   string                 `protobuf:"bytes,2,opt,name=delve_addr,json=delveAddr"`
	xxx_hidden_Location    string                 `protobuf:"bytes,3,opt,name=location"`
	xxx_hidden_ProcessId   int32                  `protobuf:"varint,4,opt,name=process_id,json=processId"`
	xxx_hidden_Args        []string               `protobuf:"bytes,5,rep,name=args"`
	xxx_hidden_Metadata    map[string]string      `protobuf:"bytes,6,rep,name=metadata" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterTargetRequest) Reset() {
	*x = RegisterTargetRequest{}
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTargetRequest) ProtoMessage() {}

func (x *RegisterTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterTargetRequest) GetProcessName() string {
	if x != nil {
		return x.xxx_hidden_ProcessName
	}
	return ""
}

func (x *RegisterTargetRequest) GetDelveAddr() string {
	if x != nil {
		return x.xxx_hidden_DelveAddr
	}
	return ""
}

func (x *RegisterTargetRequest) GetLocation() string {
	if x != nil {
		return x.xxx_hidden_Location
	}
	return ""
}

func (x *RegisterTargetRequest) GetProcessId() int32 {
	if x != nil {
		return x.xxx_hidden_ProcessId
	}
	return 0
}

func (x *RegisterTargetRequest) GetArgs() []string {
	if x != nil {
		return x.xxx_hidden_Args
	}
	return nil
}

func (x *RegisterTargetRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *RegisterTargetRequest) SetProcessName(v string) {
	x.xxx_hidden_ProcessName = v
}

func (x *RegisterTargetRequest) SetDelveAddr(v string) {
	x.xxx_hidden_DelveAddr = v
}

func (x *RegisterTargetRequest) SetLocation(v string) {
	x.xxx_hidden_Location = v
}

func (x *RegisterTargetRequest) SetProcessId(v int32) {
	x.xxx_hidden_ProcessId = v
}

func (x *RegisterTargetRequest) SetArgs(v []string) {
	x.xxx_hidden_Args = v
}

func (x *RegisterTargetRequest) SetMetadata(v map[string]string) {
	x.xxx_hidden_Metadata = v
}

type RegisterTargetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ProcessName string
	DelveAddr   string
	Location    string
	ProcessId   int32
	Args        []string
	Metadata    map[string]string
}

func (b0 RegisterTargetRequest_builder) Build() *RegisterTargetRequest {
	m0 := &RegisterTargetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ProcessName = b.ProcessName
	x.xxx_hidden_DelveAddr = b.DelveAddr
	x.xxx_hidden_Location = b.Location
	x.xxx_hidden_ProcessId = b.ProcessId
	x.xxx_hidden_Args = b.Args
	x.xxx_hidden_Metadata = b.Metadata
	return m0
}

// Target registration response
type RegisterTargetResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TargetId string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId"`
	xxx_hidden_Target   *Target                `protobuf:"bytes,2,opt,name=target"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterTargetResponse) Reset() {
	*x = RegisterTargetResponse{}
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTargetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTargetResponse) ProtoMessage() {}

func (x *RegisterTargetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterTargetResponse) GetTargetId() string {
	if x != nil {
		return x.xxx_hidden_TargetId
	}
	return ""
}

func (x *RegisterTargetResponse) GetTarget() *Target {
	if x != nil {
		return x.xxx_hidden_Target
	}
	return nil
}

func (x *RegisterTargetResponse) SetTargetId(v string) {
	x.xxx_hidden_TargetId = v
}

func (x *RegisterTargetResponse) SetTarget(v *Target) {
	x.xxx_hidden_Target = v
}

func (x *RegisterTargetResponse) HasTarget() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Target != nil
}

func (x *RegisterTargetResponse) ClearTarget() {
	x.xxx_hidden_Target = nil
}

type RegisterTargetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TargetId string
	Target   *Target
}

func (b0 RegisterTargetResponse_builder) Build() *RegisterTargetResponse {
	m0 := &RegisterTargetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TargetId = b.TargetId
	x.xxx_hidden_Target = b.Target
	return m0
}

// Target unregistration request
type UnregisterTargetRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TargetId string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UnregisterTargetRequest) Reset() {
	*x = UnregisterTargetRequest{}
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterTargetRequest) ProtoMessage() {}

func (x *UnregisterTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UnregisterTargetRequest) GetTargetId() string {
	if x != nil {
		return x.xxx_hidden_TargetId
	}
	return ""
}

func (x *UnregisterTargetRequest) SetTargetId(v string) {
	x.xxx_hidden_TargetId = v
}

type UnregisterTargetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TargetId string
}

func (b0 UnregisterTargetRequest_builder) Build() *UnregisterTargetRequest {
	m0 := &UnregisterTargetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TargetId = b.TargetId
	return m0
}

// Target unregistration response
type UnregisterTargetResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterTargetResponse) Reset() {
	*x = UnregisterTargetResponse{}
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterTargetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterTargetResponse) ProtoMessage() {}

func (x *UnregisterTargetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type UnregisterTargetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 UnregisterTargetResponse_builder) Build() *UnregisterTargetResponse {
	m0 := &UnregisterTargetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// List targets request
type ListTargetsRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_StatusFilter   []TargetStatus         `protobuf:"varint,1,rep,packed,name=status_filter,json=statusFilter,enum=runm.dapmux.v1.TargetStatus"`
	xxx_hidden_LocationFilter string                 `protobuf:"bytes,2,opt,name=location_filter,json=locationFilter"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ListTargetsRequest) Reset() {
	*x = ListTargetsRequest{}
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTargetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTargetsRequest) ProtoMessage() {}

func (x *ListTargetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListTargetsRequest) GetStatusFilter() []TargetStatus {
	if x != nil {
		return x.xxx_hidden_StatusFilter
	}
	return nil
}

func (x *ListTargetsRequest) GetLocationFilter() string {
	if x != nil {
		return x.xxx_hidden_LocationFilter
	}
	return ""
}

func (x *ListTargetsRequest) SetStatusFilter(v []TargetStatus) {
	x.xxx_hidden_StatusFilter = v
}

func (x *ListTargetsRequest) SetLocationFilter(v string) {
	x.xxx_hidden_LocationFilter = v
}

type ListTargetsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Optional filters
	StatusFilter   []TargetStatus
	LocationFilter string
}

func (b0 ListTargetsRequest_builder) Build() *ListTargetsRequest {
	m0 := &ListTargetsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_StatusFilter = b.StatusFilter
	x.xxx_hidden_LocationFilter = b.LocationFilter
	return m0
}

// List targets response
type ListTargetsResponse struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Targets        *[]*Target             `protobuf:"bytes,1,rep,name=targets"`
	xxx_hidden_ActiveTargetId string                 `protobuf:"bytes,2,opt,name=active_target_id,json=activeTargetId"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ListTargetsResponse) Reset() {
	*x = ListTargetsResponse{}
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTargetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTargetsResponse) ProtoMessage() {}

func (x *ListTargetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListTargetsResponse) GetTargets() []*Target {
	if x != nil {
		if x.xxx_hidden_Targets != nil {
			return *x.xxx_hidden_Targets
		}
	}
	return nil
}

func (x *ListTargetsResponse) GetActiveTargetId() string {
	if x != nil {
		return x.xxx_hidden_ActiveTargetId
	}
	return ""
}

func (x *ListTargetsResponse) SetTargets(v []*Target) {
	x.xxx_hidden_Targets = &v
}

func (x *ListTargetsResponse) SetActiveTargetId(v string) {
	x.xxx_hidden_ActiveTargetId = v
}

type ListTargetsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Targets        []*Target
	ActiveTargetId string
}

func (b0 ListTargetsResponse_builder) Build() *ListTargetsResponse {
	m0 := &ListTargetsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Targets = &b.Targets
	x.xxx_hidden_ActiveTargetId = b.ActiveTargetId
	return m0
}

// Set active target request
type SetActiveTargetRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TargetId string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SetActiveTargetRequest) Reset() {
	*x = SetActiveTargetRequest{}
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetActiveTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActiveTargetRequest) ProtoMessage() {}

func (x *SetActiveTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetActiveTargetRequest) GetTargetId() string {
	if x != nil {
		return x.xxx_hidden_TargetId
	}
	return ""
}

func (x *SetActiveTargetRequest) SetTargetId(v string) {
	x.xxx_hidden_TargetId = v
}

type SetActiveTargetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TargetId string
}

func (b0 SetActiveTargetRequest_builder) Build() *SetActiveTargetRequest {
	m0 := &SetActiveTargetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TargetId = b.TargetId
	return m0
}

// Set active target response
type SetActiveTargetResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Target *Target                `protobuf:"bytes,1,opt,name=target"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetActiveTargetResponse) Reset() {
	*x = SetActiveTargetResponse{}
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetActiveTargetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActiveTargetResponse) ProtoMessage() {}

func (x *SetActiveTargetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetActiveTargetResponse) GetTarget() *Target {
	if x != nil {
		return x.xxx_hidden_Target
	}
	return nil
}

func (x *SetActiveTargetResponse) SetTarget(v *Target) {
	x.xxx_hidden_Target = v
}

func (x *SetActiveTargetResponse) HasTarget() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Target != nil
}

func (x *SetActiveTargetResponse) ClearTarget() {
	x.xxx_hidden_Target = nil
}

type SetActiveTargetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Target *Target
}

func (b0 SetActiveTargetResponse_builder) Build() *SetActiveTargetResponse {
	m0 := &SetActiveTargetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Target = b.Target
	return m0
}

// Stream target events request
type StreamTargetEventsRequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EventTypes []TargetEventType      `protobuf:"varint,1,rep,packed,name=event_types,json=eventTypes,enum=runm.dapmux.v1.TargetEventType"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StreamTargetEventsRequest) Reset() {
	*x = StreamTargetEventsRequest{}
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTargetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTargetEventsRequest) ProtoMessage() {}

func (x *StreamTargetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamTargetEventsRequest) GetEventTypes() []TargetEventType {
	if x != nil {
		return x.xxx_hidden_EventTypes
	}
	return nil
}

func (x *StreamTargetEventsRequest) SetEventTypes(v []TargetEventType) {
	x.xxx_hidden_EventTypes = v
}

type StreamTargetEventsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Optional filters for events
	EventTypes []TargetEventType
}

func (b0 StreamTargetEventsRequest_builder) Build() *StreamTargetEventsRequest {
	m0 := &StreamTargetEventsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_EventTypes = b.EventTypes
	return m0
}

// Forward DAP message request
type ForwardDAPMessageRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TargetId       string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId"`
	xxx_hidden_DapMessage     []byte                 `protobuf:"bytes,2,opt,name=dap_message,json=dapMessage"`
	xxx_hidden_SequenceNumber int64                  `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ForwardDAPMessageRequest) Reset() {
	*x = ForwardDAPMessageRequest{}
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardDAPMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardDAPMessageRequest) ProtoMessage() {}

func (x *ForwardDAPMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ForwardDAPMessageRequest) GetTargetId() string {
	if x != nil {
		return x.xxx_hidden_TargetId
	}
	return ""
}

func (x *ForwardDAPMessageRequest) GetDapMessage() []byte {
	if x != nil {
		return x.xxx_hidden_DapMessage
	}
	return nil
}

func (x *ForwardDAPMessageRequest) GetSequenceNumber() int64 {
	if x != nil {
		return x.xxx_hidden_SequenceNumber
	}
	return 0
}

func (x *ForwardDAPMessageRequest) SetTargetId(v string) {
	x.xxx_hidden_TargetId = v
}

func (x *ForwardDAPMessageRequest) SetDapMessage(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_DapMessage = v
}

func (x *ForwardDAPMessageRequest) SetSequenceNumber(v int64) {
	x.xxx_hidden_SequenceNumber = v
}

type ForwardDAPMessageRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TargetId       string
	DapMessage     []byte
	SequenceNumber int64
}

func (b0 ForwardDAPMessageRequest_builder) Build() *ForwardDAPMessageRequest {
	m0 := &ForwardDAPMessageRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TargetId = b.TargetId
	x.xxx_hidden_DapMessage = b.DapMessage
	x.xxx_hidden_SequenceNumber = b.SequenceNumber
	return m0
}

// Forward DAP message response
type ForwardDAPMessageResponse struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ResponseMessage []byte                 `protobuf:"bytes,1,opt,name=response_message,json=responseMessage"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ForwardDAPMessageResponse) Reset() {
	*x = ForwardDAPMessageResponse{}
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardDAPMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardDAPMessageResponse) ProtoMessage() {}

func (x *ForwardDAPMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ForwardDAPMessageResponse) GetResponseMessage() []byte {
	if x != nil {
		return x.xxx_hidden_ResponseMessage
	}
	return nil
}

func (x *ForwardDAPMessageResponse) SetResponseMessage(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ResponseMessage = v
}

type ForwardDAPMessageResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ResponseMessage []byte
}

func (b0 ForwardDAPMessageResponse_builder) Build() *ForwardDAPMessageResponse {
	m0 := &ForwardDAPMessageResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ResponseMessage = b.ResponseMessage
	return m0
}

// Debug target representation
type Target struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id             string                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name           string                 `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Addr           string                 `protobuf:"bytes,3,opt,name=addr"`
	xxx_hidden_Process        string                 `protobuf:"bytes,4,opt,name=process"`
	xxx_hidden_Location       string                 `protobuf:"bytes,5,opt,name=location"`
	xxx_hidden_RegisteredAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=registered_at,json=registeredAt"`
	xxx_hidden_Status         TargetStatus           `protobuf:"varint,7,opt,name=status,enum=runm.dapmux.v1.TargetStatus"`
	xxx_hidden_ProcessId      int32                  `protobuf:"varint,8,opt,name=process_id,json=processId"`
	xxx_hidden_Args           []string               `protobuf:"bytes,9,rep,name=args"`
	xxx_hidden_Metadata       map[string]string      `protobuf:"bytes,10,rep,name=metadata" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_ConnectionInfo *ConnectionInfo        `protobuf:"bytes,11,opt,name=connection_info,json=connectionInfo"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Target) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *Target) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Target) GetAddr() string {
	if x != nil {
		return x.xxx_hidden_Addr
	}
	return ""
}

func (x *Target) GetProcess() string {
	if x != nil {
		return x.xxx_hidden_Process
	}
	return ""
}

func (x *Target) GetLocation() string {
	if x != nil {
		return x.xxx_hidden_Location
	}
	return ""
}

func (x *Target) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_RegisteredAt
	}
	return nil
}

func (x *Target) GetStatus() TargetStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return TargetStatus_TARGET_STATUS_UNSPECIFIED
}

func (x *Target) GetProcessId() int32 {
	if x != nil {
		return x.xxx_hidden_ProcessId
	}
	return 0
}

func (x *Target) GetArgs() []string {
	if x != nil {
		return x.xxx_hidden_Args
	}
	return nil
}

func (x *Target) GetMetadata() map[string]string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *Target) GetConnectionInfo() *ConnectionInfo {
	if x != nil {
		return x.xxx_hidden_ConnectionInfo
	}
	return nil
}

func (x *Target) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *Target) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Target) SetAddr(v string) {
	x.xxx_hidden_Addr = v
}

func (x *Target) SetProcess(v string) {
	x.xxx_hidden_Process = v
}

func (x *Target) SetLocation(v string) {
	x.xxx_hidden_Location = v
}

func (x *Target) SetRegisteredAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_RegisteredAt = v
}

func (x *Target) SetStatus(v TargetStatus) {
	x.xxx_hidden_Status = v
}

func (x *Target) SetProcessId(v int32) {
	x.xxx_hidden_ProcessId = v
}

func (x *Target) SetArgs(v []string) {
	x.xxx_hidden_Args = v
}

func (x *Target) SetMetadata(v map[string]string) {
	x.xxx_hidden_Metadata = v
}

func (x *Target) SetConnectionInfo(v *ConnectionInfo) {
	x.xxx_hidden_ConnectionInfo = v
}

func (x *Target) HasRegisteredAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RegisteredAt != nil
}

func (x *Target) HasConnectionInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ConnectionInfo != nil
}

func (x *Target) ClearRegisteredAt() {
	x.xxx_hidden_RegisteredAt = nil
}

func (x *Target) ClearConnectionInfo() {
	x.xxx_hidden_ConnectionInfo = nil
}

type Target_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id             string
	Name           string
	Addr           string
	Process        string
	Location       string
	RegisteredAt   *timestamppb.Timestamp
	Status         TargetStatus
	ProcessId      int32
	Args           []string
	Metadata       map[string]string
	ConnectionInfo *ConnectionInfo
}

func (b0 Target_builder) Build() *Target {
	m0 := &Target{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Addr = b.Addr
	x.xxx_hidden_Process = b.Process
	x.xxx_hidden_Location = b.Location
	x.xxx_hidden_RegisteredAt = b.RegisteredAt
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_ProcessId = b.ProcessId
	x.xxx_hidden_Args = b.Args
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_ConnectionInfo = b.ConnectionInfo
	return m0
}

// Connection information
type ConnectionInfo struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RemoteAddr       string                 `protobuf:"bytes,1,opt,name=remote_addr,json=remoteAddr"`
	xxx_hidden_LocalAddr        string                 `protobuf:"bytes,2,opt,name=local_addr,json=localAddr"`
	xxx_hidden_Protocol         string                 `protobuf:"bytes,3,opt,name=protocol"`
	xxx_hidden_ConnectedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=connected_at,json=connectedAt"`
	xxx_hidden_BytesSent        int64                  `protobuf:"varint,5,opt,name=bytes_sent,json=bytesSent"`
	xxx_hidden_BytesReceived    int64                  `protobuf:"varint,6,opt,name=bytes_received,json=bytesReceived"`
	xxx_hidden_MessagesSent     int64                  `protobuf:"varint,7,opt,name=messages_sent,json=messagesSent"`
	xxx_hidden_MessagesReceived int64                  `protobuf:"varint,8,opt,name=messages_received,json=messagesReceived"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ConnectionInfo) Reset() {
	*x = ConnectionInfo{}
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionInfo) ProtoMessage() {}

func (x *ConnectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConnectionInfo) GetRemoteAddr() string {
	if x != nil {
		return x.xxx_hidden_RemoteAddr
	}
	return ""
}

func (x *ConnectionInfo) GetLocalAddr() string {
	if x != nil {
		return x.xxx_hidden_LocalAddr
	}
	return ""
}

func (x *ConnectionInfo) GetProtocol() string {
	if x != nil {
		return x.xxx_hidden_Protocol
	}
	return ""
}

func (x *ConnectionInfo) GetConnectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ConnectedAt
	}
	return nil
}

func (x *ConnectionInfo) GetBytesSent() int64 {
	if x != nil {
		return x.xxx_hidden_BytesSent
	}
	return 0
}

func (x *ConnectionInfo) GetBytesReceived() int64 {
	if x != nil {
		return x.xxx_hidden_BytesReceived
	}
	return 0
}

func (x *ConnectionInfo) GetMessagesSent() int64 {
	if x != nil {
		return x.xxx_hidden_MessagesSent
	}
	return 0
}

func (x *ConnectionInfo) GetMessagesReceived() int64 {
	if x != nil {
		return x.xxx_hidden_MessagesReceived
	}
	return 0
}

func (x *ConnectionInfo) SetRemoteAddr(v string) {
	x.xxx_hidden_RemoteAddr = v
}

func (x *ConnectionInfo) SetLocalAddr(v string) {
	x.xxx_hidden_LocalAddr = v
}

func (x *ConnectionInfo) SetProtocol(v string) {
	x.xxx_hidden_Protocol = v
}

func (x *ConnectionInfo) SetConnectedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ConnectedAt = v
}

func (x *ConnectionInfo) SetBytesSent(v int64) {
	x.xxx_hidden_BytesSent = v
}

func (x *ConnectionInfo) SetBytesReceived(v int64) {
	x.xxx_hidden_BytesReceived = v
}

func (x *ConnectionInfo) SetMessagesSent(v int64) {
	x.xxx_hidden_MessagesSent = v
}

func (x *ConnectionInfo) SetMessagesReceived(v int64) {
	x.xxx_hidden_MessagesReceived = v
}

func (x *ConnectionInfo) HasConnectedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ConnectedAt != nil
}

func (x *ConnectionInfo) ClearConnectedAt() {
	x.xxx_hidden_ConnectedAt = nil
}

type ConnectionInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RemoteAddr       string
	LocalAddr        string
	Protocol         string
	ConnectedAt      *timestamppb.Timestamp
	BytesSent        int64
	BytesReceived    int64
	MessagesSent     int64
	MessagesReceived int64
}

func (b0 ConnectionInfo_builder) Build() *ConnectionInfo {
	m0 := &ConnectionInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RemoteAddr = b.RemoteAddr
	x.xxx_hidden_LocalAddr = b.LocalAddr
	x.xxx_hidden_Protocol = b.Protocol
	x.xxx_hidden_ConnectedAt = b.ConnectedAt
	x.xxx_hidden_BytesSent = b.BytesSent
	x.xxx_hidden_BytesReceived = b.BytesReceived
	x.xxx_hidden_MessagesSent = b.MessagesSent
	x.xxx_hidden_MessagesReceived = b.MessagesReceived
	return m0
}

// Target event for streaming updates
type TargetEvent struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type      TargetEventType        `protobuf:"varint,1,opt,name=type,enum=runm.dapmux.v1.TargetEventType"`
	xxx_hidden_Target    *Target                `protobuf:"bytes,2,opt,name=target"`
	xxx_hidden_Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp"`
	xxx_hidden_Details   string                 `protobuf:"bytes,4,opt,name=details"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TargetEvent) Reset() {
	*x = TargetEvent{}
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetEvent) ProtoMessage() {}

func (x *TargetEvent) ProtoReflect() protoreflect.Message {
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TargetEvent) GetType() TargetEventType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return TargetEventType_TARGET_EVENT_TYPE_UNSPECIFIED
}

func (x *TargetEvent) GetTarget() *Target {
	if x != nil {
		return x.xxx_hidden_Target
	}
	return nil
}

func (x *TargetEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return nil
}

func (x *TargetEvent) GetDetails() string {
	if x != nil {
		return x.xxx_hidden_Details
	}
	return ""
}

func (x *TargetEvent) SetType(v TargetEventType) {
	x.xxx_hidden_Type = v
}

func (x *TargetEvent) SetTarget(v *Target) {
	x.xxx_hidden_Target = v
}

func (x *TargetEvent) SetTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_Timestamp = v
}

func (x *TargetEvent) SetDetails(v string) {
	x.xxx_hidden_Details = v
}

func (x *TargetEvent) HasTarget() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Target != nil
}

func (x *TargetEvent) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timestamp != nil
}

func (x *TargetEvent) ClearTarget() {
	x.xxx_hidden_Target = nil
}

func (x *TargetEvent) ClearTimestamp() {
	x.xxx_hidden_Timestamp = nil
}

type TargetEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type      TargetEventType
	Target    *Target
	Timestamp *timestamppb.Timestamp
	Details   string
}

func (b0 TargetEvent_builder) Build() *TargetEvent {
	m0 := &TargetEvent{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Target = b.Target
	x.xxx_hidden_Timestamp = b.Timestamp
	x.xxx_hidden_Details = b.Details
	return m0
}

// Health check request
type HealthCheckRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Service string                 `protobuf:"bytes,1,opt,name=service"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.xxx_hidden_Service
	}
	return ""
}

func (x *HealthCheckRequest) SetService(v string) {
	x.xxx_hidden_Service = v
}

type HealthCheckRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Service string
}

func (b0 HealthCheckRequest_builder) Build() *HealthCheckRequest {
	m0 := &HealthCheckRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Service = b.Service
	return m0
}

// Health check response
type HealthCheckResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status  HealthStatus           `protobuf:"varint,1,opt,name=status,enum=runm.dapmux.v1.HealthStatus"`
	xxx_hidden_Message string                 `protobuf:"bytes,2,opt,name=message"`
	xxx_hidden_Details map[string]string      `protobuf:"bytes,3,rep,name=details" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dapmux_v1_dapmux_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HealthCheckResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return HealthStatus_HEALTH_STATUS_UNKNOWN
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.xxx_hidden_Details
	}
	return nil
}

func (x *HealthCheckResponse) SetStatus(v HealthStatus) {
	x.xxx_hidden_Status = v
}

func (x *HealthCheckResponse) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

func (x *HealthCheckResponse) SetDetails(v map[string]string) {
	x.xxx_hidden_Details = v
}

type HealthCheckResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status  HealthStatus
	Message string
	Details map[string]string
}

func (b0 HealthCheckResponse_builder) Build() *HealthCheckResponse {
	m0 := &HealthCheckResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_Message = b.Message
	x.xxx_hidden_Details = b.Details
	return m0
}

var File_dapmux_v1_dapmux_proto protoreflect.FileDescriptor

const file_dapmux_v1_dapmux_proto_rawDesc = "" +
	"\n" +
	"\x16dapmux/v1/dapmux.proto\x12\x0erunm.dapmux.v1\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb6\x02\n" +
	"\x15RegisterTargetRequest\x12!\n" +
	"\fprocess_name\x18\x01 \x01(\tR\vprocessName\x12\x1d\n" +
	"\n" +
	"delve_addr\x18\x02 \x01(\tR\tdelveAddr\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"process_id\x18\x04 \x01(\x05R\tprocessId\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04args\x12O\n" +
	"\bmetadata\x18\x06 \x03(\v23.runm.dapmux.v1.RegisterTargetRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\x16RegisterTargetResponse\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12.\n" +
	"\x06target\x18\x02 \x01(\v2\x16.runm.dapmux.v1.TargetR\x06target\"6\n" +
	"\x17UnregisterTargetRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\"\x1a\n" +
	"\x18UnregisterTargetResponse\"\x80\x01\n" +
	"\x12ListTargetsRequest\x12A\n" +
	"\rstatus_filter\x18\x01 \x03(\x0e2\x1c.runm.dapmux.v1.TargetStatusR\fstatusFilter\x12'\n" +
	"\x0flocation_filter\x18\x02 \x01(\tR\x0elocationFilter\"q\n" +
	"\x13ListTargetsResponse\x120\n" +
	"\atargets\x18\x01 \x03(\v2\x16.runm.dapmux.v1.TargetR\atargets\x12(\n" +
	"\x10active_target_id\x18\x02 \x01(\tR\x0eactiveTargetId\"5\n" +
	"\x16SetActiveTargetRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\"I\n" +
	"\x17SetActiveTargetResponse\x12.\n" +
	"\x06target\x18\x01 \x01(\v2\x16.runm.dapmux.v1.TargetR\x06target\"]\n" +
	"\x19StreamTargetEventsRequest\x12@\n" +
	"\vevent_types\x18\x01 \x03(\x0e2\x1f.runm.dapmux.v1.TargetEventTypeR\n" +
	"eventTypes\"\x81\x01\n" +
	"\x18ForwardDAPMessageRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x1f\n" +
	"\vdap_message\x18\x02 \x01(\fR\n" +
	"dapMessage\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x03R\x0esequenceNumber\"F\n" +
	"\x19ForwardDAPMessageResponse\x12)\n" +
	"\x10response_message\x18\x01 \x01(\fR\x0fresponseMessage\"\xe8\x03\n" +
	"\x06Target\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\tR\x04addr\x12\x18\n" +
	"\aprocess\x18\x04 \x01(\tR\aprocess\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12?\n" +
	"\rregistered_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x124\n" +
	"\x06status\x18\a \x01(\x0e2\x1c.runm.dapmux.v1.TargetStatusR\x06status\x12\x1d\n" +
	"\n" +
	"process_id\x18\b \x01(\x05R\tprocessId\x12\x12\n" +
	"\x04args\x18\t \x03(\tR\x04args\x12@\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2$.runm.dapmux.v1.Target.MetadataEntryR\bmetadata\x12G\n" +
	"\x0fconnection_info\x18\v \x01(\v2\x1e.runm.dapmux.v1.ConnectionInfoR\x0econnectionInfo\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc3\x02\n" +
	"\x0eConnectionInfo\x12\x1f\n" +
	"\vremote_addr\x18\x01 \x01(\tR\n" +
	"remoteAddr\x12\x1d\n" +
	"\n" +
	"local_addr\x18\x02 \x01(\tR\tlocalAddr\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12=\n" +
	"\fconnected_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vconnectedAt\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x05 \x01(\x03R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\x06 \x01(\x03R\rbytesReceived\x12#\n" +
	"\rmessages_sent\x18\a \x01(\x03R\fmessagesSent\x12+\n" +
	"\x11messages_received\x18\b \x01(\x03R\x10messagesReceived\"\xc6\x01\n" +
	"\vTargetEvent\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.runm.dapmux.v1.TargetEventTypeR\x04type\x12.\n" +
	"\x06target\x18\x02 \x01(\v2\x16.runm.dapmux.v1.TargetR\x06target\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xed\x01\n" +
	"\x13HealthCheckResponse\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.runm.dapmux.v1.HealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12J\n" +
	"\adetails\x18\x03 \x03(\v20.runm.dapmux.v1.HealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xbe\x01\n" +
	"\fTargetStatus\x12\x1d\n" +
	"\x19TARGET_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TARGET_STATUS_ACTIVE\x10\x01\x12\x1e\n" +
	"\x1aTARGET_STATUS_DISCONNECTED\x10\x02\x12\x17\n" +
	"\x13TARGET_STATUS_ERROR\x10\x03\x12\x1c\n" +
	"\x18TARGET_STATUS_CONNECTING\x10\x04\x12\x1e\n" +
	"\x1aTARGET_STATUS_RECONNECTING\x10\x05*\x93\x02\n" +
	"\x0fTargetEventType\x12!\n" +
	"\x1dTARGET_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TARGET_EVENT_TYPE_ADDED\x10\x01\x12\x1d\n" +
	"\x19TARGET_EVENT_TYPE_REMOVED\x10\x02\x12$\n" +
	" TARGET_EVENT_TYPE_STATUS_CHANGED\x10\x03\x12&\n" +
	"\"TARGET_EVENT_TYPE_METADATA_UPDATED\x10\x04\x12,\n" +
	"(TARGET_EVENT_TYPE_CONNECTION_ESTABLISHED\x10\x05\x12%\n" +
	"!TARGET_EVENT_TYPE_CONNECTION_LOST\x10\x06*\x86\x01\n" +
	"\fHealthStatus\x12\x19\n" +
	"\x15HEALTH_STATUS_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_SERVING\x10\x01\x12\x1d\n" +
	"\x19HEALTH_STATUS_NOT_SERVING\x10\x02\x12!\n" +
	"\x1dHEALTH_STATUS_SERVICE_UNKNOWN\x10\x032\xdd\x04\n" +
	"\rDAPMuxService\x12_\n" +
	"\x0eRegisterTarget\x12%.runm.dapmux.v1.RegisterTargetRequest\x1a&.runm.dapmux.v1.RegisterTargetResponse\x12e\n" +
	"\x10UnregisterTarget\x12'.runm.dapmux.v1.UnregisterTargetRequest\x1a(.runm.dapmux.v1.UnregisterTargetResponse\x12V\n" +
	"\vListTargets\x12\".runm.dapmux.v1.ListTargetsRequest\x1a#.runm.dapmux.v1.ListTargetsResponse\x12b\n" +
	"\x0fSetActiveTarget\x12&.runm.dapmux.v1.SetActiveTargetRequest\x1a'.runm.dapmux.v1.SetActiveTargetResponse\x12^\n" +
	"\x12StreamTargetEvents\x12).runm.dapmux.v1.StreamTargetEventsRequest\x1a\x1b.runm.dapmux.v1.TargetEvent0\x01\x12h\n" +
	"\x11ForwardDAPMessage\x12(.runm.dapmux.v1.ForwardDAPMessageRequest\x1a).runm.dapmux.v1.ForwardDAPMessageResponse2\xb5\x01\n" +
	"\rHealthService\x12P\n" +
	"\x05Check\x12\".runm.dapmux.v1.HealthCheckRequest\x1a#.runm.dapmux.v1.HealthCheckResponse\x12R\n" +
	"\x05Watch\x12\".runm.dapmux.v1.HealthCheckRequest\x1a#.runm.dapmux.v1.HealthCheckResponse0\x01B\xb6\x01\n" +
	"\x12com.runm.dapmux.v1B\vDapmuxProtoP\x01Z/github.com/walteh/runm/proto/dapmux/v1;dapmuxv1\xa2\x02\x03RDX\xaa\x02\x0eRunm.Dapmux.V1\xca\x02\x0eRunm\\Dapmux\\V1\xe2\x02\x1aRunm\\Dapmux\\V1\\GPBMetadata\xea\x02\x10Runm::Dapmux::V1\x92\x03\a\xd2>\x02\x10\x03\b\x02b\beditionsp\xe8\a"

var file_dapmux_v1_dapmux_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_dapmux_v1_dapmux_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_dapmux_v1_dapmux_proto_goTypes = []any{
	(TargetStatus)(0),                 // 0: runm.dapmux.v1.TargetStatus
	(TargetEventType)(0),              // 1: runm.dapmux.v1.TargetEventType
	(HealthStatus)(0),                 // 2: runm.dapmux.v1.HealthStatus
	(*RegisterTargetRequest)(nil),     // 3: runm.dapmux.v1.RegisterTargetRequest
	(*RegisterTargetResponse)(nil),    // 4: runm.dapmux.v1.RegisterTargetResponse
	(*UnregisterTargetRequest)(nil),   // 5: runm.dapmux.v1.UnregisterTargetRequest
	(*UnregisterTargetResponse)(nil),  // 6: runm.dapmux.v1.UnregisterTargetResponse
	(*ListTargetsRequest)(nil),        // 7: runm.dapmux.v1.ListTargetsRequest
	(*ListTargetsResponse)(nil),       // 8: runm.dapmux.v1.ListTargetsResponse
	(*SetActiveTargetRequest)(nil),    // 9: runm.dapmux.v1.SetActiveTargetRequest
	(*SetActiveTargetResponse)(nil),   // 10: runm.dapmux.v1.SetActiveTargetResponse
	(*StreamTargetEventsRequest)(nil), // 11: runm.dapmux.v1.StreamTargetEventsRequest
	(*ForwardDAPMessageRequest)(nil),  // 12: runm.dapmux.v1.ForwardDAPMessageRequest
	(*ForwardDAPMessageResponse)(nil), // 13: runm.dapmux.v1.ForwardDAPMessageResponse
	(*Target)(nil),                    // 14: runm.dapmux.v1.Target
	(*ConnectionInfo)(nil),            // 15: runm.dapmux.v1.ConnectionInfo
	(*TargetEvent)(nil),               // 16: runm.dapmux.v1.TargetEvent
	(*HealthCheckRequest)(nil),        // 17: runm.dapmux.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),       // 18: runm.dapmux.v1.HealthCheckResponse
	nil,                               // 19: runm.dapmux.v1.RegisterTargetRequest.MetadataEntry
	nil,                               // 20: runm.dapmux.v1.Target.MetadataEntry
	nil,                               // 21: runm.dapmux.v1.HealthCheckResponse.DetailsEntry
	(*timestamppb.Timestamp)(nil),     // 22: google.protobuf.Timestamp
}
var file_dapmux_v1_dapmux_proto_depIdxs = []int32{
	19, // 0: runm.dapmux.v1.RegisterTargetRequest.metadata:type_name -> runm.dapmux.v1.RegisterTargetRequest.MetadataEntry
	14, // 1: runm.dapmux.v1.RegisterTargetResponse.target:type_name -> runm.dapmux.v1.Target
	0,  // 2: runm.dapmux.v1.ListTargetsRequest.status_filter:type_name -> runm.dapmux.v1.TargetStatus
	14, // 3: runm.dapmux.v1.ListTargetsResponse.targets:type_name -> runm.dapmux.v1.Target
	14, // 4: runm.dapmux.v1.SetActiveTargetResponse.target:type_name -> runm.dapmux.v1.Target
	1,  // 5: runm.dapmux.v1.StreamTargetEventsRequest.event_types:type_name -> runm.dapmux.v1.TargetEventType
	22, // 6: runm.dapmux.v1.Target.registered_at:type_name -> google.protobuf.Timestamp
	0,  // 7: runm.dapmux.v1.Target.status:type_name -> runm.dapmux.v1.TargetStatus
	20, // 8: runm.dapmux.v1.Target.metadata:type_name -> runm.dapmux.v1.Target.MetadataEntry
	15, // 9: runm.dapmux.v1.Target.connection_info:type_name -> runm.dapmux.v1.ConnectionInfo
	22, // 10: runm.dapmux.v1.ConnectionInfo.connected_at:type_name -> google.protobuf.Timestamp
	1,  // 11: runm.dapmux.v1.TargetEvent.type:type_name -> runm.dapmux.v1.TargetEventType
	14, // 12: runm.dapmux.v1.TargetEvent.target:type_name -> runm.dapmux.v1.Target
	22, // 13: runm.dapmux.v1.TargetEvent.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 14: runm.dapmux.v1.HealthCheckResponse.status:type_name -> runm.dapmux.v1.HealthStatus
	21, // 15: runm.dapmux.v1.HealthCheckResponse.details:type_name -> runm.dapmux.v1.HealthCheckResponse.DetailsEntry
	3,  // 16: runm.dapmux.v1.DAPMuxService.RegisterTarget:input_type -> runm.dapmux.v1.RegisterTargetRequest
	5,  // 17: runm.dapmux.v1.DAPMuxService.UnregisterTarget:input_type -> runm.dapmux.v1.UnregisterTargetRequest
	7,  // 18: runm.dapmux.v1.DAPMuxService.ListTargets:input_type -> runm.dapmux.v1.ListTargetsRequest
	9,  // 19: runm.dapmux.v1.DAPMuxService.SetActiveTarget:input_type -> runm.dapmux.v1.SetActiveTargetRequest
	11, // 20: runm.dapmux.v1.DAPMuxService.StreamTargetEvents:input_type -> runm.dapmux.v1.StreamTargetEventsRequest
	12, // 21: runm.dapmux.v1.DAPMuxService.ForwardDAPMessage:input_type -> runm.dapmux.v1.ForwardDAPMessageRequest
	17, // 22: runm.dapmux.v1.HealthService.Check:input_type -> runm.dapmux.v1.HealthCheckRequest
	17, // 23: runm.dapmux.v1.HealthService.Watch:input_type -> runm.dapmux.v1.HealthCheckRequest
	4,  // 24: runm.dapmux.v1.DAPMuxService.RegisterTarget:output_type -> runm.dapmux.v1.RegisterTargetResponse
	6,  // 25: runm.dapmux.v1.DAPMuxService.UnregisterTarget:output_type -> runm.dapmux.v1.UnregisterTargetResponse
	8,  // 26: runm.dapmux.v1.DAPMuxService.ListTargets:output_type -> runm.dapmux.v1.ListTargetsResponse
	10, // 27: runm.dapmux.v1.DAPMuxService.SetActiveTarget:output_type -> runm.dapmux.v1.SetActiveTargetResponse
	16, // 28: runm.dapmux.v1.DAPMuxService.StreamTargetEvents:output_type -> runm.dapmux.v1.TargetEvent
	13, // 29: runm.dapmux.v1.DAPMuxService.ForwardDAPMessage:output_type -> runm.dapmux.v1.ForwardDAPMessageResponse
	18, // 30: runm.dapmux.v1.HealthService.Check:output_type -> runm.dapmux.v1.HealthCheckResponse
	18, // 31: runm.dapmux.v1.HealthService.Watch:output_type -> runm.dapmux.v1.HealthCheckResponse
	24, // [24:32] is the sub-list for method output_type
	16, // [16:24] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_dapmux_v1_dapmux_proto_init() }
func file_dapmux_v1_dapmux_proto_init() {
	if File_dapmux_v1_dapmux_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dapmux_v1_dapmux_proto_rawDesc), len(file_dapmux_v1_dapmux_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_dapmux_v1_dapmux_proto_goTypes,
		DependencyIndexes: file_dapmux_v1_dapmux_proto_depIdxs,
		EnumInfos:         file_dapmux_v1_dapmux_proto_enumTypes,
		MessageInfos:      file_dapmux_v1_dapmux_proto_msgTypes,
	}.Build()
	File_dapmux_v1_dapmux_proto = out.File
	file_dapmux_v1_dapmux_proto_goTypes = nil
	file_dapmux_v1_dapmux_proto_depIdxs = nil
}
