inpackage: false
with-expecter: true
testonly: false
exported: true
outpkg: mock{{.PackageName}}
dir: ./gen/mocks/{{.InterfaceDirRelative}}
disable-version-string: true
resolve-type-alias: false
issue-845-fix: true
filename: "{{.InterfaceName}}_mock.gen.go"
mockname: Mock{{.InterfaceName}}
packages: #generated
    google.golang.org/grpc:
        interfaces:
            BidiStreamingServer:
    github.com/containerd/containerd/v2/pkg/stdio:
        interfaces:
            Platform:
    github.com/containerd/console:
        interfaces:
            Console:
