dir: ./gen/mocks/{{.InterfaceDirRelative}}
structname: Mock{{.InterfaceName}}
pkgname: mock{{.SrcPackageName}}
filename: "{{.InterfaceName}}_mock.gen.go"
template: matryer
template-data:
# unroll-variadic: true
packages:
    ./proto:
        config:
            recursive: true
            exclude-interface-regex: "Unsafe*|TTRPC*"
            include-interface-regex: ".*ServiceServer|.*ServiceClient"

