// Code generated by options-gen v0.52.1. DO NOT EDIT.

package tracegroup

import (
	"context"
	"log/slog"
	"time"
)

type TraceGroupOpt func(o *TraceGroupOpts)

func newTraceGroupOpts(
	options ...TraceGroupOpt,
) TraceGroupOpts {
	var o TraceGroupOpts

	// Setting defaults from field tag (if present)

	o.name = "tracegroup"
	o.logLevel = slog.Level(-4)
	o.logStart = true
	o.logEnd = true
	o.logTaskStart = false
	o.logTaskEnd = false
	o.callerSkip = 1

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithName(opt string) TraceGroupOpt {
	return func(o *TraceGroupOpts) { o.name = opt }
}

func WithLogLevel(opt slog.Level) TraceGroupOpt {
	return func(o *TraceGroupOpts) { o.logLevel = opt }
}

func WithLogStart(opt bool) TraceGroupOpt {
	return func(o *TraceGroupOpts) { o.logStart = opt }
}

func WithLogEnd(opt bool) TraceGroupOpt {
	return func(o *TraceGroupOpts) { o.logEnd = opt }
}

func WithLogTaskStart(opt bool) TraceGroupOpt {
	return func(o *TraceGroupOpts) { o.logTaskStart = opt }
}

func WithLogTaskEnd(opt bool) TraceGroupOpt {
	return func(o *TraceGroupOpts) { o.logTaskEnd = opt }
}

func WithTimeout(opt time.Duration) TraceGroupOpt {
	return func(o *TraceGroupOpts) { o.timeout = opt }
}

func WithCallerSkip(opt int) TraceGroupOpt {
	return func(o *TraceGroupOpts) { o.callerSkip = opt }
}

func WithSlogBaseContext(opt context.Context) TraceGroupOpt {
	return func(o *TraceGroupOpts) { o.slogBaseContext = opt }
}

func WithAttrFunc(opt func() []slog.Attr) TraceGroupOpt {
	return func(o *TraceGroupOpts) { o.attrFunc = opt }
}

func WithMaxConcurrent(opt int) TraceGroupOpt {
	return func(o *TraceGroupOpts) { o.maxConcurrent = opt }
}

func (o *TraceGroupOpts) Validate() error {
	return nil
}

// Public getter methods for private fields

func (o TraceGroupOpts) Name() string { return o.name }

func (o TraceGroupOpts) LogLevel() slog.Level { return o.logLevel }

func (o TraceGroupOpts) LogStart() bool { return o.logStart }

func (o TraceGroupOpts) LogEnd() bool { return o.logEnd }

func (o TraceGroupOpts) LogTaskStart() bool { return o.logTaskStart }

func (o TraceGroupOpts) LogTaskEnd() bool { return o.logTaskEnd }

func (o TraceGroupOpts) Timeout() time.Duration { return o.timeout }

func (o TraceGroupOpts) CallerSkip() int { return o.callerSkip }

func (o TraceGroupOpts) SlogBaseContext() context.Context { return o.slogBaseContext }

func (o TraceGroupOpts) AttrFunc() func() []slog.Attr { return o.attrFunc }

func (o TraceGroupOpts) MaxConcurrent() int { return o.maxConcurrent }
