// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: vmm/v1/host_callback.proto

package vmmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostCallbackService_ForkExecProxy_FullMethodName = "/runm.vmm.v1.HostCallbackService/ForkExecProxy"
)

// HostCallbackServiceClient is the client API for HostCallbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostCallbackServiceClient interface {
	ForkExecProxy(ctx context.Context, in *ForkExecProxyRequest, opts ...grpc.CallOption) (*ForkExecProxyResponse, error)
}

type hostCallbackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostCallbackServiceClient(cc grpc.ClientConnInterface) HostCallbackServiceClient {
	return &hostCallbackServiceClient{cc}
}

func (c *hostCallbackServiceClient) ForkExecProxy(ctx context.Context, in *ForkExecProxyRequest, opts ...grpc.CallOption) (*ForkExecProxyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForkExecProxyResponse)
	err := c.cc.Invoke(ctx, HostCallbackService_ForkExecProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostCallbackServiceServer is the server API for HostCallbackService service.
// All implementations should embed UnimplementedHostCallbackServiceServer
// for forward compatibility.
type HostCallbackServiceServer interface {
	ForkExecProxy(context.Context, *ForkExecProxyRequest) (*ForkExecProxyResponse, error)
}

// UnimplementedHostCallbackServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostCallbackServiceServer struct{}

func (UnimplementedHostCallbackServiceServer) ForkExecProxy(context.Context, *ForkExecProxyRequest) (*ForkExecProxyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForkExecProxy not implemented")
}
func (UnimplementedHostCallbackServiceServer) testEmbeddedByValue() {}

// UnsafeHostCallbackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostCallbackServiceServer will
// result in compilation errors.
type UnsafeHostCallbackServiceServer interface {
	mustEmbedUnimplementedHostCallbackServiceServer()
}

func RegisterHostCallbackServiceServer(s grpc.ServiceRegistrar, srv HostCallbackServiceServer) {
	// If the following call pancis, it indicates UnimplementedHostCallbackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostCallbackService_ServiceDesc, srv)
}

func _HostCallbackService_ForkExecProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForkExecProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostCallbackServiceServer).ForkExecProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostCallbackService_ForkExecProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostCallbackServiceServer).ForkExecProxy(ctx, req.(*ForkExecProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostCallbackService_ServiceDesc is the grpc.ServiceDesc for HostCallbackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostCallbackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runm.vmm.v1.HostCallbackService",
	HandlerType: (*HostCallbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ForkExecProxy",
			Handler:    _HostCallbackService_ForkExecProxy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vmm/v1/host_callback.proto",
}
