// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: vmm/v1/host_callback.proto
package vmmv1

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type TTRPCHostCallbackServiceService interface {
	ForkExecProxy(context.Context, *ForkExecProxyRequest) (*ForkExecProxyResponse, error)
}

func RegisterTTRPCHostCallbackServiceService(srv *ttrpc.Server, svc TTRPCHostCallbackServiceService) {
	srv.RegisterService("runm.vmm.v1.HostCallbackService", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"ForkExecProxy": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req ForkExecProxyRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.ForkExecProxy(ctx, &req)
			},
		},
	})
}

type ttrpchostcallbackserviceClient struct {
	client *ttrpc.Client
}

func NewTTRPCHostCallbackServiceClient(client *ttrpc.Client) TTRPCHostCallbackServiceService {
	return &ttrpchostcallbackserviceClient{
		client: client,
	}
}

func (c *ttrpchostcallbackserviceClient) ForkExecProxy(ctx context.Context, req *ForkExecProxyRequest) (*ForkExecProxyResponse, error) {
	var resp ForkExecProxyResponse
	if err := c.client.Call(ctx, "runm.vmm.v1.HostCallbackService", "ForkExecProxy", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
