// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: devlog/v1/dapmux.proto

package devlogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Target registration request
type StructuredLog struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructuredLog) Reset() {
	*x = StructuredLog{}
	mi := &file_devlog_v1_dapmux_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructuredLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructuredLog) ProtoMessage() {}

func (x *StructuredLog) ProtoReflect() protoreflect.Message {
	mi := &file_devlog_v1_dapmux_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type StructuredLog_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 StructuredLog_builder) Build() *StructuredLog {
	m0 := &StructuredLog{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type RawLog struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawLog) Reset() {
	*x = RawLog{}
	mi := &file_devlog_v1_dapmux_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawLog) ProtoMessage() {}

func (x *RawLog) ProtoReflect() protoreflect.Message {
	mi := &file_devlog_v1_dapmux_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RawLog_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RawLog_builder) Build() *RawLog {
	m0 := &RawLog{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type LogRequest struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Log isLogRequest_Log       `protobuf_oneof:"log"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_devlog_v1_dapmux_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_devlog_v1_dapmux_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LogRequest) GetStructured() *StructuredLog {
	if x != nil {
		if x, ok := x.xxx_hidden_Log.(*logRequest_Structured); ok {
			return x.Structured
		}
	}
	return nil
}

func (x *LogRequest) GetRaw() *RawLog {
	if x != nil {
		if x, ok := x.xxx_hidden_Log.(*logRequest_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

func (x *LogRequest) SetStructured(v *StructuredLog) {
	if v == nil {
		x.xxx_hidden_Log = nil
		return
	}
	x.xxx_hidden_Log = &logRequest_Structured{v}
}

func (x *LogRequest) SetRaw(v *RawLog) {
	if v == nil {
		x.xxx_hidden_Log = nil
		return
	}
	x.xxx_hidden_Log = &logRequest_Raw{v}
}

func (x *LogRequest) HasLog() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Log != nil
}

func (x *LogRequest) HasStructured() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Log.(*logRequest_Structured)
	return ok
}

func (x *LogRequest) HasRaw() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Log.(*logRequest_Raw)
	return ok
}

func (x *LogRequest) ClearLog() {
	x.xxx_hidden_Log = nil
}

func (x *LogRequest) ClearStructured() {
	if _, ok := x.xxx_hidden_Log.(*logRequest_Structured); ok {
		x.xxx_hidden_Log = nil
	}
}

func (x *LogRequest) ClearRaw() {
	if _, ok := x.xxx_hidden_Log.(*logRequest_Raw); ok {
		x.xxx_hidden_Log = nil
	}
}

const LogRequest_Log_not_set_case case_LogRequest_Log = 0
const LogRequest_Structured_case case_LogRequest_Log = 1
const LogRequest_Raw_case case_LogRequest_Log = 2

func (x *LogRequest) WhichLog() case_LogRequest_Log {
	if x == nil {
		return LogRequest_Log_not_set_case
	}
	switch x.xxx_hidden_Log.(type) {
	case *logRequest_Structured:
		return LogRequest_Structured_case
	case *logRequest_Raw:
		return LogRequest_Raw_case
	default:
		return LogRequest_Log_not_set_case
	}
}

type LogRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Log:
	Structured *StructuredLog
	Raw        *RawLog
	// -- end of xxx_hidden_Log
}

func (b0 LogRequest_builder) Build() *LogRequest {
	m0 := &LogRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Structured != nil {
		x.xxx_hidden_Log = &logRequest_Structured{b.Structured}
	}
	if b.Raw != nil {
		x.xxx_hidden_Log = &logRequest_Raw{b.Raw}
	}
	return m0
}

type case_LogRequest_Log protoreflect.FieldNumber

func (x case_LogRequest_Log) String() string {
	md := file_devlog_v1_dapmux_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isLogRequest_Log interface {
	isLogRequest_Log()
}

type logRequest_Structured struct {
	Structured *StructuredLog `protobuf:"bytes,1,opt,name=structured,oneof"`
}

type logRequest_Raw struct {
	Raw *RawLog `protobuf:"bytes,2,opt,name=raw,oneof"`
}

func (*logRequest_Structured) isLogRequest_Log() {}

func (*logRequest_Raw) isLogRequest_Log() {}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_devlog_v1_dapmux_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_devlog_v1_dapmux_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type LogResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 LogResponse_builder) Build() *LogResponse {
	m0 := &LogResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_devlog_v1_dapmux_proto protoreflect.FileDescriptor

const file_devlog_v1_dapmux_proto_rawDesc = "" +
	"\n" +
	"\x16devlog/v1/dapmux.proto\x12\x0erunm.devlog.v1\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0f\n" +
	"\rStructuredLog\"\b\n" +
	"\x06RawLog\"\x80\x01\n" +
	"\n" +
	"LogRequest\x12?\n" +
	"\n" +
	"structured\x18\x01 \x01(\v2\x1d.runm.devlog.v1.StructuredLogH\x00R\n" +
	"structured\x12*\n" +
	"\x03raw\x18\x02 \x01(\v2\x16.runm.devlog.v1.RawLogH\x00R\x03rawB\x05\n" +
	"\x03log\"\r\n" +
	"\vLogResponse2S\n" +
	"\rDevlogService\x12B\n" +
	"\x03Log\x12\x1a.runm.devlog.v1.LogRequest\x1a\x1b.runm.devlog.v1.LogResponse(\x010\x01B\xb6\x01\n" +
	"\x12com.runm.devlog.v1B\vDapmuxProtoP\x01Z/github.com/walteh/runm/proto/devlog/v1;devlogv1\xa2\x02\x03RDX\xaa\x02\x0eRunm.Devlog.V1\xca\x02\x0eRunm\\Devlog\\V1\xe2\x02\x1aRunm\\Devlog\\V1\\GPBMetadata\xea\x02\x10Runm::Devlog::V1\x92\x03\a\xd2>\x02\x10\x03\b\x02b\beditionsp\xe8\a"

var file_devlog_v1_dapmux_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_devlog_v1_dapmux_proto_goTypes = []any{
	(*StructuredLog)(nil), // 0: runm.devlog.v1.StructuredLog
	(*RawLog)(nil),        // 1: runm.devlog.v1.RawLog
	(*LogRequest)(nil),    // 2: runm.devlog.v1.LogRequest
	(*LogResponse)(nil),   // 3: runm.devlog.v1.LogResponse
}
var file_devlog_v1_dapmux_proto_depIdxs = []int32{
	0, // 0: runm.devlog.v1.LogRequest.structured:type_name -> runm.devlog.v1.StructuredLog
	1, // 1: runm.devlog.v1.LogRequest.raw:type_name -> runm.devlog.v1.RawLog
	2, // 2: runm.devlog.v1.DevlogService.Log:input_type -> runm.devlog.v1.LogRequest
	3, // 3: runm.devlog.v1.DevlogService.Log:output_type -> runm.devlog.v1.LogResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_devlog_v1_dapmux_proto_init() }
func file_devlog_v1_dapmux_proto_init() {
	if File_devlog_v1_dapmux_proto != nil {
		return
	}
	file_devlog_v1_dapmux_proto_msgTypes[2].OneofWrappers = []any{
		(*logRequest_Structured)(nil),
		(*logRequest_Raw)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_devlog_v1_dapmux_proto_rawDesc), len(file_devlog_v1_dapmux_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_devlog_v1_dapmux_proto_goTypes,
		DependencyIndexes: file_devlog_v1_dapmux_proto_depIdxs,
		MessageInfos:      file_devlog_v1_dapmux_proto_msgTypes,
	}.Build()
	File_devlog_v1_dapmux_proto = out.File
	file_devlog_v1_dapmux_proto_goTypes = nil
	file_devlog_v1_dapmux_proto_depIdxs = nil
}
