// Code generated by protoc-gen-go-opaque-helpers. DO NOT EDIT.
// source: v1/host.proto

package runmv1

import (
	protovalidate "buf.build/go/protovalidate"
)

// NewForkExecProxyRequest creates a new ForkExecProxyRequest using the builder
func NewForkExecProxyRequest(b *ForkExecProxyRequest_builder) *ForkExecProxyRequest {
	return b.Build()
}

// NewForkExecProxyRequestE creates a new ForkExecProxyRequest using the builder with validation
func NewForkExecProxyRequestE(b *ForkExecProxyRequest_builder) (*ForkExecProxyRequest, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NewForkExecProxyResponse creates a new ForkExecProxyResponse using the builder
func NewForkExecProxyResponse(b *ForkExecProxyResponse_builder) *ForkExecProxyResponse {
	return b.Build()
}

// NewForkExecProxyResponseE creates a new ForkExecProxyResponse using the builder with validation
func NewForkExecProxyResponseE(b *ForkExecProxyResponse_builder) (*ForkExecProxyResponse, error) {
	m := b.Build()
	if err := protovalidate.Validate(m); err != nil {
		return nil, err
	}
	return m, nil
}
