// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/socket.proto

package runmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	_ "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VsockPort struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Port uint32                 `protobuf:"varint,1,opt,name=port"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VsockPort) Reset() {
	*x = VsockPort{}
	mi := &file_v1_socket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VsockPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VsockPort) ProtoMessage() {}

func (x *VsockPort) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VsockPort) GetPort() uint32 {
	if x != nil {
		return x.xxx_hidden_Port
	}
	return 0
}

func (x *VsockPort) SetPort(v uint32) {
	x.xxx_hidden_Port = v
}

type VsockPort_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Port uint32
}

func (b0 VsockPort_builder) Build() *VsockPort {
	m0 := &VsockPort{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Port = b.Port
	return m0
}

type UnixSocketPath struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path string                 `protobuf:"bytes,1,opt,name=path"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UnixSocketPath) Reset() {
	*x = UnixSocketPath{}
	mi := &file_v1_socket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnixSocketPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnixSocketPath) ProtoMessage() {}

func (x *UnixSocketPath) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UnixSocketPath) GetPath() string {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return ""
}

func (x *UnixSocketPath) SetPath(v string) {
	x.xxx_hidden_Path = v
}

type UnixSocketPath_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Path string
}

func (b0 UnixSocketPath_builder) Build() *UnixSocketPath {
	m0 := &UnixSocketPath{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Path = b.Path
	return m0
}

type SocketType struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type isSocketType_Type      `protobuf_oneof:"type"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SocketType) Reset() {
	*x = SocketType{}
	mi := &file_v1_socket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocketType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocketType) ProtoMessage() {}

func (x *SocketType) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SocketType) GetVsockPort() *VsockPort {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*socketType_VsockPort); ok {
			return x.VsockPort
		}
	}
	return nil
}

func (x *SocketType) GetUnixSocketPath() *UnixSocketPath {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*socketType_UnixSocketPath); ok {
			return x.UnixSocketPath
		}
	}
	return nil
}

func (x *SocketType) SetVsockPort(v *VsockPort) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &socketType_VsockPort{v}
}

func (x *SocketType) SetUnixSocketPath(v *UnixSocketPath) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &socketType_UnixSocketPath{v}
}

func (x *SocketType) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *SocketType) HasVsockPort() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*socketType_VsockPort)
	return ok
}

func (x *SocketType) HasUnixSocketPath() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*socketType_UnixSocketPath)
	return ok
}

func (x *SocketType) ClearType() {
	x.xxx_hidden_Type = nil
}

func (x *SocketType) ClearVsockPort() {
	if _, ok := x.xxx_hidden_Type.(*socketType_VsockPort); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *SocketType) ClearUnixSocketPath() {
	if _, ok := x.xxx_hidden_Type.(*socketType_UnixSocketPath); ok {
		x.xxx_hidden_Type = nil
	}
}

const SocketType_Type_not_set_case case_SocketType_Type = 0
const SocketType_VsockPort_case case_SocketType_Type = 1
const SocketType_UnixSocketPath_case case_SocketType_Type = 2

func (x *SocketType) WhichType() case_SocketType_Type {
	if x == nil {
		return SocketType_Type_not_set_case
	}
	switch x.xxx_hidden_Type.(type) {
	case *socketType_VsockPort:
		return SocketType_VsockPort_case
	case *socketType_UnixSocketPath:
		return SocketType_UnixSocketPath_case
	default:
		return SocketType_Type_not_set_case
	}
}

type SocketType_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Type:
	VsockPort      *VsockPort
	UnixSocketPath *UnixSocketPath
	// -- end of xxx_hidden_Type
}

func (b0 SocketType_builder) Build() *SocketType {
	m0 := &SocketType{}
	b, x := &b0, m0
	_, _ = b, x
	if b.VsockPort != nil {
		x.xxx_hidden_Type = &socketType_VsockPort{b.VsockPort}
	}
	if b.UnixSocketPath != nil {
		x.xxx_hidden_Type = &socketType_UnixSocketPath{b.UnixSocketPath}
	}
	return m0
}

type case_SocketType_Type protoreflect.FieldNumber

func (x case_SocketType_Type) String() string {
	md := file_v1_socket_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isSocketType_Type interface {
	isSocketType_Type()
}

type socketType_VsockPort struct {
	VsockPort *VsockPort `protobuf:"bytes,1,opt,name=vsock_port,json=vsockPort,oneof"`
}

type socketType_UnixSocketPath struct {
	UnixSocketPath *UnixSocketPath `protobuf:"bytes,2,opt,name=unix_socket_path,json=unixSocketPath,oneof"`
}

func (*socketType_VsockPort) isSocketType_Type() {}

func (*socketType_UnixSocketPath) isSocketType_Type() {}

type DialOpenListenerRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ListeningOn *SocketType            `protobuf:"bytes,1,opt,name=listening_on,json=listeningOn"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DialOpenListenerRequest) Reset() {
	*x = DialOpenListenerRequest{}
	mi := &file_v1_socket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialOpenListenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialOpenListenerRequest) ProtoMessage() {}

func (x *DialOpenListenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DialOpenListenerRequest) GetListeningOn() *SocketType {
	if x != nil {
		return x.xxx_hidden_ListeningOn
	}
	return nil
}

func (x *DialOpenListenerRequest) SetListeningOn(v *SocketType) {
	x.xxx_hidden_ListeningOn = v
}

func (x *DialOpenListenerRequest) HasListeningOn() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ListeningOn != nil
}

func (x *DialOpenListenerRequest) ClearListeningOn() {
	x.xxx_hidden_ListeningOn = nil
}

type DialOpenListenerRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ListeningOn *SocketType
}

func (b0 DialOpenListenerRequest_builder) Build() *DialOpenListenerRequest {
	m0 := &DialOpenListenerRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ListeningOn = b.ListeningOn
	return m0
}

type DialOpenListenerResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialOpenListenerResponse) Reset() {
	*x = DialOpenListenerResponse{}
	mi := &file_v1_socket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialOpenListenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialOpenListenerResponse) ProtoMessage() {}

func (x *DialOpenListenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DialOpenListenerResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DialOpenListenerResponse_builder) Build() *DialOpenListenerResponse {
	m0 := &DialOpenListenerResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type AllocateSocketStreamRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateSocketStreamRequest) Reset() {
	*x = AllocateSocketStreamRequest{}
	mi := &file_v1_socket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateSocketStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateSocketStreamRequest) ProtoMessage() {}

func (x *AllocateSocketStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type AllocateSocketStreamRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 AllocateSocketStreamRequest_builder) Build() *AllocateSocketStreamRequest {
	m0 := &AllocateSocketStreamRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type AllocateSocketStreamResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SocketType *SocketType            `protobuf:"bytes,1,opt,name=socket_type,json=socketType"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AllocateSocketStreamResponse) Reset() {
	*x = AllocateSocketStreamResponse{}
	mi := &file_v1_socket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateSocketStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateSocketStreamResponse) ProtoMessage() {}

func (x *AllocateSocketStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AllocateSocketStreamResponse) GetSocketType() *SocketType {
	if x != nil {
		return x.xxx_hidden_SocketType
	}
	return nil
}

func (x *AllocateSocketStreamResponse) SetSocketType(v *SocketType) {
	x.xxx_hidden_SocketType = v
}

func (x *AllocateSocketStreamResponse) HasSocketType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SocketType != nil
}

func (x *AllocateSocketStreamResponse) ClearSocketType() {
	x.xxx_hidden_SocketType = nil
}

type AllocateSocketStreamResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SocketType *SocketType
}

func (b0 AllocateSocketStreamResponse_builder) Build() *AllocateSocketStreamResponse {
	m0 := &AllocateSocketStreamResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SocketType = b.SocketType
	return m0
}

type AllocateIORequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OpenStdin  bool                   `protobuf:"varint,1,opt,name=open_stdin,json=openStdin"`
	xxx_hidden_OpenStdout bool                   `protobuf:"varint,2,opt,name=open_stdout,json=openStdout"`
	xxx_hidden_OpenStderr bool                   `protobuf:"varint,3,opt,name=open_stderr,json=openStderr"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AllocateIORequest) Reset() {
	*x = AllocateIORequest{}
	mi := &file_v1_socket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateIORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateIORequest) ProtoMessage() {}

func (x *AllocateIORequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AllocateIORequest) GetOpenStdin() bool {
	if x != nil {
		return x.xxx_hidden_OpenStdin
	}
	return false
}

func (x *AllocateIORequest) GetOpenStdout() bool {
	if x != nil {
		return x.xxx_hidden_OpenStdout
	}
	return false
}

func (x *AllocateIORequest) GetOpenStderr() bool {
	if x != nil {
		return x.xxx_hidden_OpenStderr
	}
	return false
}

func (x *AllocateIORequest) SetOpenStdin(v bool) {
	x.xxx_hidden_OpenStdin = v
}

func (x *AllocateIORequest) SetOpenStdout(v bool) {
	x.xxx_hidden_OpenStdout = v
}

func (x *AllocateIORequest) SetOpenStderr(v bool) {
	x.xxx_hidden_OpenStderr = v
}

type AllocateIORequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OpenStdin  bool
	OpenStdout bool
	OpenStderr bool
}

func (b0 AllocateIORequest_builder) Build() *AllocateIORequest {
	m0 := &AllocateIORequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OpenStdin = b.OpenStdin
	x.xxx_hidden_OpenStdout = b.OpenStdout
	x.xxx_hidden_OpenStderr = b.OpenStderr
	return m0
}

type AllocateIOResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_IoReferenceId string                 `protobuf:"bytes,1,opt,name=io_reference_id,json=ioReferenceId"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AllocateIOResponse) Reset() {
	*x = AllocateIOResponse{}
	mi := &file_v1_socket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateIOResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateIOResponse) ProtoMessage() {}

func (x *AllocateIOResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AllocateIOResponse) GetIoReferenceId() string {
	if x != nil {
		return x.xxx_hidden_IoReferenceId
	}
	return ""
}

func (x *AllocateIOResponse) SetIoReferenceId(v string) {
	x.xxx_hidden_IoReferenceId = v
}

type AllocateIOResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	IoReferenceId string
}

func (b0 AllocateIOResponse_builder) Build() *AllocateIOResponse {
	m0 := &AllocateIOResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_IoReferenceId = b.IoReferenceId
	return m0
}

type AllocateConsoleRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateConsoleRequest) Reset() {
	*x = AllocateConsoleRequest{}
	mi := &file_v1_socket_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateConsoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateConsoleRequest) ProtoMessage() {}

func (x *AllocateConsoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type AllocateConsoleRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 AllocateConsoleRequest_builder) Build() *AllocateConsoleRequest {
	m0 := &AllocateConsoleRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type AllocateConsoleResponse struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ConsoleReferenceId string                 `protobuf:"bytes,1,opt,name=console_reference_id,json=consoleReferenceId"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *AllocateConsoleResponse) Reset() {
	*x = AllocateConsoleResponse{}
	mi := &file_v1_socket_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateConsoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateConsoleResponse) ProtoMessage() {}

func (x *AllocateConsoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AllocateConsoleResponse) GetConsoleReferenceId() string {
	if x != nil {
		return x.xxx_hidden_ConsoleReferenceId
	}
	return ""
}

func (x *AllocateConsoleResponse) SetConsoleReferenceId(v string) {
	x.xxx_hidden_ConsoleReferenceId = v
}

type AllocateConsoleResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ConsoleReferenceId string
}

func (b0 AllocateConsoleResponse_builder) Build() *AllocateConsoleResponse {
	m0 := &AllocateConsoleResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ConsoleReferenceId = b.ConsoleReferenceId
	return m0
}

type CloseSocketsRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SocketTypes *[]*SocketType         `protobuf:"bytes,1,rep,name=socket_types,json=socketTypes"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CloseSocketsRequest) Reset() {
	*x = CloseSocketsRequest{}
	mi := &file_v1_socket_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSocketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSocketsRequest) ProtoMessage() {}

func (x *CloseSocketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CloseSocketsRequest) GetSocketTypes() []*SocketType {
	if x != nil {
		if x.xxx_hidden_SocketTypes != nil {
			return *x.xxx_hidden_SocketTypes
		}
	}
	return nil
}

func (x *CloseSocketsRequest) SetSocketTypes(v []*SocketType) {
	x.xxx_hidden_SocketTypes = &v
}

type CloseSocketsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SocketTypes []*SocketType
}

func (b0 CloseSocketsRequest_builder) Build() *CloseSocketsRequest {
	m0 := &CloseSocketsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SocketTypes = &b.SocketTypes
	return m0
}

type CloseSocketsResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSocketsResponse) Reset() {
	*x = CloseSocketsResponse{}
	mi := &file_v1_socket_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSocketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSocketsResponse) ProtoMessage() {}

func (x *CloseSocketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CloseSocketsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 CloseSocketsResponse_builder) Build() *CloseSocketsResponse {
	m0 := &CloseSocketsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type AllocateSocketsRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Count uint32                 `protobuf:"varint,1,opt,name=count"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AllocateSocketsRequest) Reset() {
	*x = AllocateSocketsRequest{}
	mi := &file_v1_socket_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateSocketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateSocketsRequest) ProtoMessage() {}

func (x *AllocateSocketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AllocateSocketsRequest) GetCount() uint32 {
	if x != nil {
		return x.xxx_hidden_Count
	}
	return 0
}

func (x *AllocateSocketsRequest) SetCount(v uint32) {
	x.xxx_hidden_Count = v
}

type AllocateSocketsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Count uint32
}

func (b0 AllocateSocketsRequest_builder) Build() *AllocateSocketsRequest {
	m0 := &AllocateSocketsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Count = b.Count
	return m0
}

type AllocateSocketsResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SocketTypes *[]*SocketType         `protobuf:"bytes,1,rep,name=socket_types,json=socketTypes"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AllocateSocketsResponse) Reset() {
	*x = AllocateSocketsResponse{}
	mi := &file_v1_socket_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateSocketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateSocketsResponse) ProtoMessage() {}

func (x *AllocateSocketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AllocateSocketsResponse) GetSocketTypes() []*SocketType {
	if x != nil {
		if x.xxx_hidden_SocketTypes != nil {
			return *x.xxx_hidden_SocketTypes
		}
	}
	return nil
}

func (x *AllocateSocketsResponse) SetSocketTypes(v []*SocketType) {
	x.xxx_hidden_SocketTypes = &v
}

type AllocateSocketsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SocketTypes []*SocketType
}

func (b0 AllocateSocketsResponse_builder) Build() *AllocateSocketsResponse {
	m0 := &AllocateSocketsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SocketTypes = &b.SocketTypes
	return m0
}

type BindIOToSocketsRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_IoReferenceId string                 `protobuf:"bytes,1,opt,name=io_reference_id,json=ioReferenceId"`
	xxx_hidden_StdinSocket   *SocketType            `protobuf:"bytes,2,opt,name=stdin_socket,json=stdinSocket"`
	xxx_hidden_StdoutSocket  *SocketType            `protobuf:"bytes,3,opt,name=stdout_socket,json=stdoutSocket"`
	xxx_hidden_StderrSocket  *SocketType            `protobuf:"bytes,4,opt,name=stderr_socket,json=stderrSocket"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *BindIOToSocketsRequest) Reset() {
	*x = BindIOToSocketsRequest{}
	mi := &file_v1_socket_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindIOToSocketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindIOToSocketsRequest) ProtoMessage() {}

func (x *BindIOToSocketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BindIOToSocketsRequest) GetIoReferenceId() string {
	if x != nil {
		return x.xxx_hidden_IoReferenceId
	}
	return ""
}

func (x *BindIOToSocketsRequest) GetStdinSocket() *SocketType {
	if x != nil {
		return x.xxx_hidden_StdinSocket
	}
	return nil
}

func (x *BindIOToSocketsRequest) GetStdoutSocket() *SocketType {
	if x != nil {
		return x.xxx_hidden_StdoutSocket
	}
	return nil
}

func (x *BindIOToSocketsRequest) GetStderrSocket() *SocketType {
	if x != nil {
		return x.xxx_hidden_StderrSocket
	}
	return nil
}

func (x *BindIOToSocketsRequest) SetIoReferenceId(v string) {
	x.xxx_hidden_IoReferenceId = v
}

func (x *BindIOToSocketsRequest) SetStdinSocket(v *SocketType) {
	x.xxx_hidden_StdinSocket = v
}

func (x *BindIOToSocketsRequest) SetStdoutSocket(v *SocketType) {
	x.xxx_hidden_StdoutSocket = v
}

func (x *BindIOToSocketsRequest) SetStderrSocket(v *SocketType) {
	x.xxx_hidden_StderrSocket = v
}

func (x *BindIOToSocketsRequest) HasStdinSocket() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StdinSocket != nil
}

func (x *BindIOToSocketsRequest) HasStdoutSocket() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StdoutSocket != nil
}

func (x *BindIOToSocketsRequest) HasStderrSocket() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StderrSocket != nil
}

func (x *BindIOToSocketsRequest) ClearStdinSocket() {
	x.xxx_hidden_StdinSocket = nil
}

func (x *BindIOToSocketsRequest) ClearStdoutSocket() {
	x.xxx_hidden_StdoutSocket = nil
}

func (x *BindIOToSocketsRequest) ClearStderrSocket() {
	x.xxx_hidden_StderrSocket = nil
}

type BindIOToSocketsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	IoReferenceId string
	StdinSocket   *SocketType
	StdoutSocket  *SocketType
	StderrSocket  *SocketType
}

func (b0 BindIOToSocketsRequest_builder) Build() *BindIOToSocketsRequest {
	m0 := &BindIOToSocketsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_IoReferenceId = b.IoReferenceId
	x.xxx_hidden_StdinSocket = b.StdinSocket
	x.xxx_hidden_StdoutSocket = b.StdoutSocket
	x.xxx_hidden_StderrSocket = b.StderrSocket
	return m0
}

type BindIOToSocketsResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindIOToSocketsResponse) Reset() {
	*x = BindIOToSocketsResponse{}
	mi := &file_v1_socket_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindIOToSocketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindIOToSocketsResponse) ProtoMessage() {}

func (x *BindIOToSocketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type BindIOToSocketsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 BindIOToSocketsResponse_builder) Build() *BindIOToSocketsResponse {
	m0 := &BindIOToSocketsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type BindConsoleToSocketRequest struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ConsoleReferenceId string                 `protobuf:"bytes,1,opt,name=console_reference_id,json=consoleReferenceId"`
	xxx_hidden_SocketType         *SocketType            `protobuf:"bytes,2,opt,name=socket_type,json=socketType"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *BindConsoleToSocketRequest) Reset() {
	*x = BindConsoleToSocketRequest{}
	mi := &file_v1_socket_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindConsoleToSocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindConsoleToSocketRequest) ProtoMessage() {}

func (x *BindConsoleToSocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BindConsoleToSocketRequest) GetConsoleReferenceId() string {
	if x != nil {
		return x.xxx_hidden_ConsoleReferenceId
	}
	return ""
}

func (x *BindConsoleToSocketRequest) GetSocketType() *SocketType {
	if x != nil {
		return x.xxx_hidden_SocketType
	}
	return nil
}

func (x *BindConsoleToSocketRequest) SetConsoleReferenceId(v string) {
	x.xxx_hidden_ConsoleReferenceId = v
}

func (x *BindConsoleToSocketRequest) SetSocketType(v *SocketType) {
	x.xxx_hidden_SocketType = v
}

func (x *BindConsoleToSocketRequest) HasSocketType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SocketType != nil
}

func (x *BindConsoleToSocketRequest) ClearSocketType() {
	x.xxx_hidden_SocketType = nil
}

type BindConsoleToSocketRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ConsoleReferenceId string
	SocketType         *SocketType
}

func (b0 BindConsoleToSocketRequest_builder) Build() *BindConsoleToSocketRequest {
	m0 := &BindConsoleToSocketRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ConsoleReferenceId = b.ConsoleReferenceId
	x.xxx_hidden_SocketType = b.SocketType
	return m0
}

type BindConsoleToSocketResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindConsoleToSocketResponse) Reset() {
	*x = BindConsoleToSocketResponse{}
	mi := &file_v1_socket_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindConsoleToSocketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindConsoleToSocketResponse) ProtoMessage() {}

func (x *BindConsoleToSocketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type BindConsoleToSocketResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 BindConsoleToSocketResponse_builder) Build() *BindConsoleToSocketResponse {
	m0 := &BindConsoleToSocketResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type AllocateSocketRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Count uint32                 `protobuf:"varint,1,opt,name=count"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AllocateSocketRequest) Reset() {
	*x = AllocateSocketRequest{}
	mi := &file_v1_socket_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateSocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateSocketRequest) ProtoMessage() {}

func (x *AllocateSocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AllocateSocketRequest) GetCount() uint32 {
	if x != nil {
		return x.xxx_hidden_Count
	}
	return 0
}

func (x *AllocateSocketRequest) SetCount(v uint32) {
	x.xxx_hidden_Count = v
}

type AllocateSocketRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Count uint32
}

func (b0 AllocateSocketRequest_builder) Build() *AllocateSocketRequest {
	m0 := &AllocateSocketRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Count = b.Count
	return m0
}

type AllocateSocketResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SocketType *SocketType            `protobuf:"bytes,1,opt,name=socket_type,json=socketType"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AllocateSocketResponse) Reset() {
	*x = AllocateSocketResponse{}
	mi := &file_v1_socket_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateSocketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateSocketResponse) ProtoMessage() {}

func (x *AllocateSocketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AllocateSocketResponse) GetSocketType() *SocketType {
	if x != nil {
		return x.xxx_hidden_SocketType
	}
	return nil
}

func (x *AllocateSocketResponse) SetSocketType(v *SocketType) {
	x.xxx_hidden_SocketType = v
}

func (x *AllocateSocketResponse) HasSocketType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SocketType != nil
}

func (x *AllocateSocketResponse) ClearSocketType() {
	x.xxx_hidden_SocketType = nil
}

type AllocateSocketResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SocketType *SocketType
}

func (b0 AllocateSocketResponse_builder) Build() *AllocateSocketResponse {
	m0 := &AllocateSocketResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SocketType = b.SocketType
	return m0
}

type CloseSocketRequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SocketType *SocketType            `protobuf:"bytes,1,opt,name=socket_type,json=socketType"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CloseSocketRequest) Reset() {
	*x = CloseSocketRequest{}
	mi := &file_v1_socket_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSocketRequest) ProtoMessage() {}

func (x *CloseSocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CloseSocketRequest) GetSocketType() *SocketType {
	if x != nil {
		return x.xxx_hidden_SocketType
	}
	return nil
}

func (x *CloseSocketRequest) SetSocketType(v *SocketType) {
	x.xxx_hidden_SocketType = v
}

func (x *CloseSocketRequest) HasSocketType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SocketType != nil
}

func (x *CloseSocketRequest) ClearSocketType() {
	x.xxx_hidden_SocketType = nil
}

type CloseSocketRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SocketType *SocketType
}

func (b0 CloseSocketRequest_builder) Build() *CloseSocketRequest {
	m0 := &CloseSocketRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SocketType = b.SocketType
	return m0
}

type CloseSocketResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_GoError string                 `protobuf:"bytes,1,opt,name=go_error,json=goError"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CloseSocketResponse) Reset() {
	*x = CloseSocketResponse{}
	mi := &file_v1_socket_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSocketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSocketResponse) ProtoMessage() {}

func (x *CloseSocketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CloseSocketResponse) GetGoError() string {
	if x != nil {
		return x.xxx_hidden_GoError
	}
	return ""
}

func (x *CloseSocketResponse) SetGoError(v string) {
	x.xxx_hidden_GoError = v
}

type CloseSocketResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	GoError string
}

func (b0 CloseSocketResponse_builder) Build() *CloseSocketResponse {
	m0 := &CloseSocketResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_GoError = b.GoError
	return m0
}

type CloseIORequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_IoReferenceId string                 `protobuf:"bytes,1,opt,name=io_reference_id,json=ioReferenceId"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CloseIORequest) Reset() {
	*x = CloseIORequest{}
	mi := &file_v1_socket_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseIORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseIORequest) ProtoMessage() {}

func (x *CloseIORequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CloseIORequest) GetIoReferenceId() string {
	if x != nil {
		return x.xxx_hidden_IoReferenceId
	}
	return ""
}

func (x *CloseIORequest) SetIoReferenceId(v string) {
	x.xxx_hidden_IoReferenceId = v
}

type CloseIORequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	IoReferenceId string
}

func (b0 CloseIORequest_builder) Build() *CloseIORequest {
	m0 := &CloseIORequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_IoReferenceId = b.IoReferenceId
	return m0
}

type CloseIOResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseIOResponse) Reset() {
	*x = CloseIOResponse{}
	mi := &file_v1_socket_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseIOResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseIOResponse) ProtoMessage() {}

func (x *CloseIOResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CloseIOResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 CloseIOResponse_builder) Build() *CloseIOResponse {
	m0 := &CloseIOResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type CloseConsoleRequest struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ConsoleReferenceId string                 `protobuf:"bytes,1,opt,name=console_reference_id,json=consoleReferenceId"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *CloseConsoleRequest) Reset() {
	*x = CloseConsoleRequest{}
	mi := &file_v1_socket_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseConsoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseConsoleRequest) ProtoMessage() {}

func (x *CloseConsoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CloseConsoleRequest) GetConsoleReferenceId() string {
	if x != nil {
		return x.xxx_hidden_ConsoleReferenceId
	}
	return ""
}

func (x *CloseConsoleRequest) SetConsoleReferenceId(v string) {
	x.xxx_hidden_ConsoleReferenceId = v
}

type CloseConsoleRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ConsoleReferenceId string
}

func (b0 CloseConsoleRequest_builder) Build() *CloseConsoleRequest {
	m0 := &CloseConsoleRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ConsoleReferenceId = b.ConsoleReferenceId
	return m0
}

type CloseConsoleResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseConsoleResponse) Reset() {
	*x = CloseConsoleResponse{}
	mi := &file_v1_socket_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseConsoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseConsoleResponse) ProtoMessage() {}

func (x *CloseConsoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_socket_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CloseConsoleResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 CloseConsoleResponse_builder) Build() *CloseConsoleResponse {
	m0 := &CloseConsoleResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_v1_socket_proto protoreflect.FileDescriptor

const file_v1_socket_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/socket.proto\x12\arunm.v1\x1a\x1egoogle/protobuf/duration.proto\x1a!google/protobuf/go_features.proto\"\x1f\n" +
	"\tVsockPort\x12\x12\n" +
	"\x04port\x18\x01 \x01(\rR\x04port\"$\n" +
	"\x0eUnixSocketPath\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x8e\x01\n" +
	"\n" +
	"SocketType\x123\n" +
	"\n" +
	"vsock_port\x18\x01 \x01(\v2\x12.runm.v1.VsockPortH\x00R\tvsockPort\x12C\n" +
	"\x10unix_socket_path\x18\x02 \x01(\v2\x17.runm.v1.UnixSocketPathH\x00R\x0eunixSocketPathB\x06\n" +
	"\x04type\"Q\n" +
	"\x17DialOpenListenerRequest\x126\n" +
	"\flistening_on\x18\x01 \x01(\v2\x13.runm.v1.SocketTypeR\vlisteningOn\"\x1a\n" +
	"\x18DialOpenListenerResponse\"\x1d\n" +
	"\x1bAllocateSocketStreamRequest\"T\n" +
	"\x1cAllocateSocketStreamResponse\x124\n" +
	"\vsocket_type\x18\x01 \x01(\v2\x13.runm.v1.SocketTypeR\n" +
	"socketType\"t\n" +
	"\x11AllocateIORequest\x12\x1d\n" +
	"\n" +
	"open_stdin\x18\x01 \x01(\bR\topenStdin\x12\x1f\n" +
	"\vopen_stdout\x18\x02 \x01(\bR\n" +
	"openStdout\x12\x1f\n" +
	"\vopen_stderr\x18\x03 \x01(\bR\n" +
	"openStderr\"<\n" +
	"\x12AllocateIOResponse\x12&\n" +
	"\x0fio_reference_id\x18\x01 \x01(\tR\rioReferenceId\"\x18\n" +
	"\x16AllocateConsoleRequest\"K\n" +
	"\x17AllocateConsoleResponse\x120\n" +
	"\x14console_reference_id\x18\x01 \x01(\tR\x12consoleReferenceId\"M\n" +
	"\x13CloseSocketsRequest\x126\n" +
	"\fsocket_types\x18\x01 \x03(\v2\x13.runm.v1.SocketTypeR\vsocketTypes\"\x16\n" +
	"\x14CloseSocketsResponse\".\n" +
	"\x16AllocateSocketsRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\"Q\n" +
	"\x17AllocateSocketsResponse\x126\n" +
	"\fsocket_types\x18\x01 \x03(\v2\x13.runm.v1.SocketTypeR\vsocketTypes\"\xec\x01\n" +
	"\x16BindIOToSocketsRequest\x12&\n" +
	"\x0fio_reference_id\x18\x01 \x01(\tR\rioReferenceId\x126\n" +
	"\fstdin_socket\x18\x02 \x01(\v2\x13.runm.v1.SocketTypeR\vstdinSocket\x128\n" +
	"\rstdout_socket\x18\x03 \x01(\v2\x13.runm.v1.SocketTypeR\fstdoutSocket\x128\n" +
	"\rstderr_socket\x18\x04 \x01(\v2\x13.runm.v1.SocketTypeR\fstderrSocket\"\x19\n" +
	"\x17BindIOToSocketsResponse\"\x84\x01\n" +
	"\x1aBindConsoleToSocketRequest\x120\n" +
	"\x14console_reference_id\x18\x01 \x01(\tR\x12consoleReferenceId\x124\n" +
	"\vsocket_type\x18\x02 \x01(\v2\x13.runm.v1.SocketTypeR\n" +
	"socketType\"\x1d\n" +
	"\x1bBindConsoleToSocketResponse\"-\n" +
	"\x15AllocateSocketRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\"N\n" +
	"\x16AllocateSocketResponse\x124\n" +
	"\vsocket_type\x18\x01 \x01(\v2\x13.runm.v1.SocketTypeR\n" +
	"socketType\"J\n" +
	"\x12CloseSocketRequest\x124\n" +
	"\vsocket_type\x18\x01 \x01(\v2\x13.runm.v1.SocketTypeR\n" +
	"socketType\"0\n" +
	"\x13CloseSocketResponse\x12\x19\n" +
	"\bgo_error\x18\x01 \x01(\tR\agoError\"8\n" +
	"\x0eCloseIORequest\x12&\n" +
	"\x0fio_reference_id\x18\x01 \x01(\tR\rioReferenceId\"\x11\n" +
	"\x0fCloseIOResponse\"G\n" +
	"\x13CloseConsoleRequest\x120\n" +
	"\x14console_reference_id\x18\x01 \x01(\tR\x12consoleReferenceId\"\x16\n" +
	"\x14CloseConsoleResponse2\xbb\a\n" +
	"\x16SocketAllocatorService\x12V\n" +
	"\x0fAllocateSockets\x12\x1f.runm.v1.AllocateSocketsRequest\x1a .runm.v1.AllocateSocketsResponse\"\x00\x12g\n" +
	"\x14AllocateSocketStream\x12$.runm.v1.AllocateSocketStreamRequest\x1a%.runm.v1.AllocateSocketStreamResponse\"\x000\x01\x12Y\n" +
	"\x10DialOpenListener\x12 .runm.v1.DialOpenListenerRequest\x1a!.runm.v1.DialOpenListenerResponse\"\x00\x12G\n" +
	"\n" +
	"AllocateIO\x12\x1a.runm.v1.AllocateIORequest\x1a\x1b.runm.v1.AllocateIOResponse\"\x00\x12V\n" +
	"\x0fAllocateConsole\x12\x1f.runm.v1.AllocateConsoleRequest\x1a .runm.v1.AllocateConsoleResponse\"\x00\x12b\n" +
	"\x13BindConsoleToSocket\x12#.runm.v1.BindConsoleToSocketRequest\x1a$.runm.v1.BindConsoleToSocketResponse\"\x00\x12V\n" +
	"\x0fBindIOToSockets\x12\x1f.runm.v1.BindIOToSocketsRequest\x1a .runm.v1.BindIOToSocketsResponse\"\x00\x12J\n" +
	"\vCloseSocket\x12\x1b.runm.v1.CloseSocketRequest\x1a\x1c.runm.v1.CloseSocketResponse\"\x00\x12M\n" +
	"\fCloseSockets\x12\x1c.runm.v1.CloseSocketsRequest\x1a\x1d.runm.v1.CloseSocketsResponse\"\x00\x12>\n" +
	"\aCloseIO\x12\x17.runm.v1.CloseIORequest\x1a\x18.runm.v1.CloseIOResponse\"\x00\x12M\n" +
	"\fCloseConsole\x12\x1c.runm.v1.CloseConsoleRequest\x1a\x1d.runm.v1.CloseConsoleResponse\"\x00B\x89\x01\n" +
	"\vcom.runm.v1B\vSocketProtoP\x01Z&github.com/walteh/runm/proto/v1;runmv1\xa2\x02\x03RXX\xaa\x02\aRunm.V1\xca\x02\aRunm\\V1\xe2\x02\x13Runm\\V1\\GPBMetadata\xea\x02\bRunm::V1\x92\x03\a\xd2>\x02\x10\x03\b\x02b\beditionsp\xe8\a"

var file_v1_socket_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_v1_socket_proto_goTypes = []any{
	(*VsockPort)(nil),                    // 0: runm.v1.VsockPort
	(*UnixSocketPath)(nil),               // 1: runm.v1.UnixSocketPath
	(*SocketType)(nil),                   // 2: runm.v1.SocketType
	(*DialOpenListenerRequest)(nil),      // 3: runm.v1.DialOpenListenerRequest
	(*DialOpenListenerResponse)(nil),     // 4: runm.v1.DialOpenListenerResponse
	(*AllocateSocketStreamRequest)(nil),  // 5: runm.v1.AllocateSocketStreamRequest
	(*AllocateSocketStreamResponse)(nil), // 6: runm.v1.AllocateSocketStreamResponse
	(*AllocateIORequest)(nil),            // 7: runm.v1.AllocateIORequest
	(*AllocateIOResponse)(nil),           // 8: runm.v1.AllocateIOResponse
	(*AllocateConsoleRequest)(nil),       // 9: runm.v1.AllocateConsoleRequest
	(*AllocateConsoleResponse)(nil),      // 10: runm.v1.AllocateConsoleResponse
	(*CloseSocketsRequest)(nil),          // 11: runm.v1.CloseSocketsRequest
	(*CloseSocketsResponse)(nil),         // 12: runm.v1.CloseSocketsResponse
	(*AllocateSocketsRequest)(nil),       // 13: runm.v1.AllocateSocketsRequest
	(*AllocateSocketsResponse)(nil),      // 14: runm.v1.AllocateSocketsResponse
	(*BindIOToSocketsRequest)(nil),       // 15: runm.v1.BindIOToSocketsRequest
	(*BindIOToSocketsResponse)(nil),      // 16: runm.v1.BindIOToSocketsResponse
	(*BindConsoleToSocketRequest)(nil),   // 17: runm.v1.BindConsoleToSocketRequest
	(*BindConsoleToSocketResponse)(nil),  // 18: runm.v1.BindConsoleToSocketResponse
	(*AllocateSocketRequest)(nil),        // 19: runm.v1.AllocateSocketRequest
	(*AllocateSocketResponse)(nil),       // 20: runm.v1.AllocateSocketResponse
	(*CloseSocketRequest)(nil),           // 21: runm.v1.CloseSocketRequest
	(*CloseSocketResponse)(nil),          // 22: runm.v1.CloseSocketResponse
	(*CloseIORequest)(nil),               // 23: runm.v1.CloseIORequest
	(*CloseIOResponse)(nil),              // 24: runm.v1.CloseIOResponse
	(*CloseConsoleRequest)(nil),          // 25: runm.v1.CloseConsoleRequest
	(*CloseConsoleResponse)(nil),         // 26: runm.v1.CloseConsoleResponse
}
var file_v1_socket_proto_depIdxs = []int32{
	0,  // 0: runm.v1.SocketType.vsock_port:type_name -> runm.v1.VsockPort
	1,  // 1: runm.v1.SocketType.unix_socket_path:type_name -> runm.v1.UnixSocketPath
	2,  // 2: runm.v1.DialOpenListenerRequest.listening_on:type_name -> runm.v1.SocketType
	2,  // 3: runm.v1.AllocateSocketStreamResponse.socket_type:type_name -> runm.v1.SocketType
	2,  // 4: runm.v1.CloseSocketsRequest.socket_types:type_name -> runm.v1.SocketType
	2,  // 5: runm.v1.AllocateSocketsResponse.socket_types:type_name -> runm.v1.SocketType
	2,  // 6: runm.v1.BindIOToSocketsRequest.stdin_socket:type_name -> runm.v1.SocketType
	2,  // 7: runm.v1.BindIOToSocketsRequest.stdout_socket:type_name -> runm.v1.SocketType
	2,  // 8: runm.v1.BindIOToSocketsRequest.stderr_socket:type_name -> runm.v1.SocketType
	2,  // 9: runm.v1.BindConsoleToSocketRequest.socket_type:type_name -> runm.v1.SocketType
	2,  // 10: runm.v1.AllocateSocketResponse.socket_type:type_name -> runm.v1.SocketType
	2,  // 11: runm.v1.CloseSocketRequest.socket_type:type_name -> runm.v1.SocketType
	13, // 12: runm.v1.SocketAllocatorService.AllocateSockets:input_type -> runm.v1.AllocateSocketsRequest
	5,  // 13: runm.v1.SocketAllocatorService.AllocateSocketStream:input_type -> runm.v1.AllocateSocketStreamRequest
	3,  // 14: runm.v1.SocketAllocatorService.DialOpenListener:input_type -> runm.v1.DialOpenListenerRequest
	7,  // 15: runm.v1.SocketAllocatorService.AllocateIO:input_type -> runm.v1.AllocateIORequest
	9,  // 16: runm.v1.SocketAllocatorService.AllocateConsole:input_type -> runm.v1.AllocateConsoleRequest
	17, // 17: runm.v1.SocketAllocatorService.BindConsoleToSocket:input_type -> runm.v1.BindConsoleToSocketRequest
	15, // 18: runm.v1.SocketAllocatorService.BindIOToSockets:input_type -> runm.v1.BindIOToSocketsRequest
	21, // 19: runm.v1.SocketAllocatorService.CloseSocket:input_type -> runm.v1.CloseSocketRequest
	11, // 20: runm.v1.SocketAllocatorService.CloseSockets:input_type -> runm.v1.CloseSocketsRequest
	23, // 21: runm.v1.SocketAllocatorService.CloseIO:input_type -> runm.v1.CloseIORequest
	25, // 22: runm.v1.SocketAllocatorService.CloseConsole:input_type -> runm.v1.CloseConsoleRequest
	14, // 23: runm.v1.SocketAllocatorService.AllocateSockets:output_type -> runm.v1.AllocateSocketsResponse
	6,  // 24: runm.v1.SocketAllocatorService.AllocateSocketStream:output_type -> runm.v1.AllocateSocketStreamResponse
	4,  // 25: runm.v1.SocketAllocatorService.DialOpenListener:output_type -> runm.v1.DialOpenListenerResponse
	8,  // 26: runm.v1.SocketAllocatorService.AllocateIO:output_type -> runm.v1.AllocateIOResponse
	10, // 27: runm.v1.SocketAllocatorService.AllocateConsole:output_type -> runm.v1.AllocateConsoleResponse
	18, // 28: runm.v1.SocketAllocatorService.BindConsoleToSocket:output_type -> runm.v1.BindConsoleToSocketResponse
	16, // 29: runm.v1.SocketAllocatorService.BindIOToSockets:output_type -> runm.v1.BindIOToSocketsResponse
	22, // 30: runm.v1.SocketAllocatorService.CloseSocket:output_type -> runm.v1.CloseSocketResponse
	12, // 31: runm.v1.SocketAllocatorService.CloseSockets:output_type -> runm.v1.CloseSocketsResponse
	24, // 32: runm.v1.SocketAllocatorService.CloseIO:output_type -> runm.v1.CloseIOResponse
	26, // 33: runm.v1.SocketAllocatorService.CloseConsole:output_type -> runm.v1.CloseConsoleResponse
	23, // [23:34] is the sub-list for method output_type
	12, // [12:23] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_v1_socket_proto_init() }
func file_v1_socket_proto_init() {
	if File_v1_socket_proto != nil {
		return
	}
	file_v1_socket_proto_msgTypes[2].OneofWrappers = []any{
		(*socketType_VsockPort)(nil),
		(*socketType_UnixSocketPath)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_socket_proto_rawDesc), len(file_v1_socket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_socket_proto_goTypes,
		DependencyIndexes: file_v1_socket_proto_depIdxs,
		MessageInfos:      file_v1_socket_proto_msgTypes,
	}.Build()
	File_v1_socket_proto = out.File
	file_v1_socket_proto_goTypes = nil
	file_v1_socket_proto_depIdxs = nil
}
